### ISSUE TITLE
Format task doesn't fix new lines to eof

### ISSUE THREAD

**Issue by mattdkerr** [jeremymailen/kotlinter-gradle#106]
The checkstyle https://checkstyle.sourceforge.io/config_misc.html#NewlineAtEndOfFile NewlineAtEndOfFile item doesn't seem to have a configuration option or accessibility to be applied during the formatKotlin task added by kotlinter. How can I get this working? It's a pretty common ask during pull request code reviews.

**Comment by jeremymailen** [comment]
Thanks for letting me know. Yeah, that's definitely a common one.

It looks like a rule exists and it's part of the standard set in ktlint 0.33.0:
https://github.com/pinterest/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt

It appears to only enforce ending in a newline if editorconfig is present and specifies the value. Kotlinter-gradle isn't currently reading the editorconfig unfortunately.

Some changes to configuration and editorconfig are coming in the next version of ktlint which sounds like it's coming soon. Let's add complete configuration options to kotlinter-gradle at that time!

**Comment by jeremymailen** [comment]
Should now work out of the box, see https://github.com/jeremymailen/kotlinter-gradle/releases/tag/2.0.0
