### ISSUE TITLE
Allow for task dependency order (format before lint for example)

### ISSUE THREAD

**Issue by bellini-ea** [jeremymailen/kotlinter-gradle#114]
Looking format first and then do the linting in our builds.  

lintKotlin current depends on "check" which means we cannot formatKotlin first which is a desired flow. 

With kotlinter ignoreFailures = false set, the build will fail due to a style issue.  We want to format first and then only fail on things that were not able to be formatted automatically.

Hence the ask to make the lintKotlin attachment to the "check" task by default with an option to change to something else like dependsOn("formatKotlin"). 

For my situation, I would end up doing the following for my builds:
* formatKotlin depends on Check
* lintKotlin depends on formatKotlin

**Comment by jeremymailen** [comment]
I see, the use case makes sense.

Kotlinter hooks into the build lifecycle in the most common way by default, but it should be possible to modify this as needed in the gradle DSL using the rules you outlined about.

Can you add this to your `build.gradle` and see if it accomplishes what you need?
```groovy
lintKotlin.dependsOn formatKotlin
```

**Comment by bellini-ea** [comment]
Thank you for the followup and the suggestion.  I did end up getting it to work with your suggestion (variant of).

`// Kotlin linting and auto code formatting
    kotlinter {
        ignoreFailures = false
        indentSize = 4
        continuationIndentSize = 4
        reporter = "checkstyle"
    }

    // Goal here is to format first, then lint the formatted code
    // If we still fail linting, then its something the formatter
    // was not able to deal with and so needs manual intervention.
    tasks.classes {
        dependsOn("formatKotlin")
    }

    tasks.withType<LintTask> {
        dependsOn("formatKotlin")
        exclude("**/*.Generated.kt")
    }`

**Comment by jeremymailen** [comment]
Looks like a good solution 👍
