### ISSUE TITLE
.editorconfig disabled_rules for import-ordering is ignored

### ISSUE THREAD

**Issue by ArslanAle** [jeremymailen/kotlinter-gradle#119]
Since version "2.1.2", disabled_rules in .editorconfig for import-ordering has no effect.

```
[*.{java, kt}]
disabled_rules=import-ordering
```
`[import-ordering] Imports must be ordered in lexicographic order without any empty lines in-between`

**Comment by jeremymailen** [comment]
Thank you for the report and your patience @ArslanAle.

You need to remove the space in the file selector and it will work, `[*.{java,kt}]`. Actually the same quirk exists in prior releases to.

I agree it's annoying and confusing, but it's a result of the editorconfig implementation in `ktlint` and will need a fix there.
