### ISSUE TITLE
lintKotlin task triggers deprecation warning with Gradle 6.0

### ISSUE THREAD

**Issue by jmeekhof** [jeremymailen/kotlinter-gradle#120]
After upgrading to gradle 6.0, the use of lintKotlin task triggers a deprecation warning about the use of `@PathSensitive` with the `@OutputFiles` annotations.

```
> Task :lintKotlinIntTest
Property 'reports' is annotated with @PathSensitive that is not allowed for @OutputFiles properties. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/LintTask.kt#L32-L34

**Comment by jeremymailen** [comment]
Thank you for the report and fix!

**Comment by plastiv** [comment]
@jmeekhof @jeremymailen was there a suggested replacement? 

I observe that currently task is not cacheable on CI since output files are back to `ABSOLUTE` path sensitivity.

**Comment by jmeekhof** [comment]
Any examples?

**Comment by plastiv** [comment]
Sure. Is there any projects integrating plugin you check yourself for regression? 

If not I will try to create minimal sample to reproduce the issue.

**Comment by jeremymailen** [comment]
Thanks for highlighting the issue. Would like to have a solution that is not depreciated and caches correctly. Not sure the right way without doing some research, but very open to suggestions and pull requests.

**Comment by plastiv** [comment]
As soon as I exacted minimal project with single kotlin file the issue is gone and cache behaves like it should. Of course 😅 

I will keep an eye on it but as of now I don't have steps-to-reproduce anymore (outside of my working project which I wouldn't share). Thank you for taking a time to reply 👍
