### ISSUE TITLE
Use Kotlin DSL?

### ISSUE THREAD

**Issue by jmeekhof** [jeremymailen/kotlinter-gradle#126]
As a kotlin linter plugin, would anyone be opposed to converting the gradle build script for this project to using the kotlin dsl? 

I'm willing to do the work, just want the "blessing" of others involved.

**Comment by jeremymailen** [comment]
Yes, that would be nice. I just hadn't gotten around to it and for a little while the kotlin DSL for gradle was still maturing.

**Comment by jmeekhof** [comment]
Ok, I'll be working on it. I notices that @mateuszkwiecinski has a couple of pull requests that have updated the `build.gradle` file, so I'll base my branches from there so we don't "lose" any updates.

**Comment by jeremymailen** [comment]
Done now, forgot to close!
