### ISSUE TITLE
LintTask should implement VerificationTask, Reporting<CheckstyleReports>

### ISSUE THREAD

**Issue by runningcode** [jeremymailen/kotlinter-gradle#138]
LintTask should implement the VerificationTask and Reporting<CheckstyleReports> interfaces to make it easier to configure reporting and verification tasks in a general way.
This makes it easier to configure IgnoreFailures or HTML and XML reporting across all tasks in the project in a single way.

See the checkstyle task for an example:
https://github.com/gradle/gradle/blob/3f79806c3599f54ca006412c23a0fe1d20698e98/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java#L58

What are your thoughts?

**Comment by jeremymailen** [comment]
Hi @runningcode and thank you for the suggestion. I assume the objective is to go from:
```groovy
lintTask {
  reports = [
    'json': file('build/lint-report.json)
  ]
}
```
To:
```groovy
lintTask {
  reports {
    json {
      destination 'build/lint-report.json'
    }
  }
}
```
Wouldn't `ignoreFailures` remain the same -- a boolean property at the root of the task?

That's certainly more attractive and familiar! It probably breaks compatibility necessitating a 3.0.

Did I capture your suggestion correctly?

**Comment by jeremymailen** [comment]
With `ignoreFailures` perhaps you are thinking about someone programmatically processing tasks and turning off/on anything implementing `VerificationTask`?
