### ISSUE TITLE
installKotlinterPrePushHook not working using 2.4.0

### ISSUE THREAD

**Issue by shabtaisharon** [jeremymailen/kotlinter-gradle#142]
```
➜  escape_pod git:(update_ktlint) ./gradlew installKotlinterPrePushHook

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installKotlinterPrePushHook' not found in root project 'escape_pod'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
```

Let me know if you need more information

**Comment by shabtaisharon** [comment]
```
License tasks
-------------
downloadLicenses - Generates reports on your runtime dependencies.
license - Checks for header consistency.
licenseFormat - Applies the license found in the header file in files missing the header.
```

```
    kotlinter {
        experimentalRules = true
    }
```

**Comment by shabtaisharon** [comment]
```
    kotlinter {
        experimentalRules = true
    }
```

```
Formatting tasks
----------------
formatKotlin - Formats the Kotlin source files.
lintKotlin - Runs lint on the Kotlin source files.
```

**Comment by jeremymailen** [comment]
It should be listed under the "build setup" tasks
```
Build Setup tasks
-----------------
init - Initializes a new Gradle build.
installKotlinterPrePushHook - Installs Kotlinter Git pre-push hook
wrapper - Generates Gradle wrapper files.
```

Are you executing the command from the root project? Much like `init` and `wrapper` it only shows up there.

**Comment by shabtaisharon** [comment]
Yes, I'm executing the command from the root project and I don't see it also in the build tasks
```
Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.
```

**Comment by jeremymailen** [comment]
Ok, hmm. If anyone else is experiencing this, please chime in as it might help.     

Let's see if we can figure it out with a little more debug output.

In the result of `./gradlew -d tasks | grep "Apply plugin"` do you see
`org.jmailen.kotlinter to root project` and either `kotlin` or `kotlin-android`?
One of those standard plugins must be present to auto register our tasks.

And in the result of `./gradlew -d tasks | grep "Register task"` do you see
`:installKotlinterPrePushHook`?

Finally
`gradle -d tasks | grep "Resolve kotlinter-gradle-2.4.0.jar"` should have some lines.

**Comment by shabtaisharon** [comment]
1. Yes
```
2020-06-14T20:46:30.067-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin org.jmailen.kotlinter to root project 'escape_pod'' started
2020-06-14T20:46:30.068-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply plugin org.jmailen.kotlinter to root project 'escape_pod''
2020-06-14T20:46:30.068-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin org.jmailen.kotlinter to root project 'escape_pod'' completed
```
2. we are using `kotlin`
3. no `installKotlinterPrePushHook` is shown using `./gradlew -d tasks | grep "Register task"`
4. 
```
➜  escape_pod git:(dev) gradle -d tasks | grep "Resolve kotlinter-gradle-2.4.0.jar"
2020-06-14T20:50:12.069-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve kotlinter-gradle-2.4.0.jar (org.jmailen.gradle:kotlinter-gradle:2.4.0)' completed
2020-06-14T20:50:12.066-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve kotlinter-gradle-2.4.0.jar (org.jmailen.gradle:kotlinter-gradle:2.4.0)' started
2020-06-14T20:50:12.069-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve kotlinter-gradle-2.4.0.jar (org.jmailen.gradle:kotlinter-gradle:2.4.0)'
```

**Comment by jeremymailen** [comment]
Ok, sorry about all the trouble. If you put this in your main build.gradle* file does it work?

`build.gradle`
```groovy
import org.jmailen.gradle.kotlinter.tasks.InstallPrePushHookTask
task installKotlinterPrePushHook(type: InstallPrePushHookTask, group: 'build setup')
```
or if kotlin `build.gradle.kts`
```kotlin
import org.jmailen.gradle.kotlinter.tasks.InstallPrePushHookTask
val installKotlinterPrePushHook by tasks.creating(InstallPrePushHookTask::class)
```

The logic of the plugin is relatively simple so I'm trying to figure out what could be going wrong
https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterPlugin.kt#L44
Iterates over the supported plugins like `kotlin` and `kotlin-android` and if this the root project, registers the hooks task equivalent to those manual steps ☝️.

**Comment by shabtaisharon** [comment]
it looks like the import is failing
![Screen Shot 2020-06-16 at 9 48 30 AM](https://user-images.githubusercontent.com/14626506/84797036-99f37780-afb6-11ea-997b-e9c2d972f864.png)
![Screen Shot 2020-06-16 at 9 48 10 AM](https://user-images.githubusercontent.com/14626506/84797037-9a8c0e00-afb6-11ea-841e-238f20f7c37b.png)

**Comment by jeremymailen** [comment]
Does it run? IntelliJ's Groovy support isn't perfect and sometimes shows spurious errors:
<img width="1387" alt="Screen Shot 2020-06-17 at 12 59 51 AM" src="https://user-images.githubusercontent.com/4814876/84872272-88ea4b00-b036-11ea-9e8d-bdf0e70446e5.png">

If that class isn't found, kotlinter 2.4.0 isn't in the build script classpath.

**Comment by shabtaisharon** [comment]
You are right, just running it solved the issue and i can see the new task.
Now to figure out why do I need to do it manually like that?

**Comment by jeremymailen** [comment]
Actually, I have a thought: is `apply plugin: "org.jmailen.kotlinter"` and `apply plugin: 'kotlin'` present for the root project as well? That would cause the hook task to be missing. Quite understandable since the root project probably doesn't have kotlin source code, although it would be harmless to include it.

**Comment by jeremymailen** [comment]
Pretty sure that's the reason. I updated the instructions here https://github.com/jeremymailen/kotlinter-gradle#git-hooks and also pushed 2.4.1 which will add this task even if there isn't a kotlin source code plugin present on the root project.

**Comment by shabtaisharon** [comment]
I'll upgrade today and test. Thank you very much @jeremymailen

**Comment by shabtaisharon** [comment]
yep, i can see it now
```
Build Setup tasks
-----------------
init - Initializes a new Gradle build.
installKotlinterPrePushHook - Installs Kotlinter Git pre-push hook
wrapper - Generates Gradle wrapper files.
```

**Comment by AlexKuz13** [comment]
> Pretty sure that's the reason. I updated the instructions here https://github.com/jeremymailen/kotlinter-gradle#git-hooks and also pushed 2.4.1 which will add this task even if there isn't a kotlin source code plugin present on the root project.

The same problem in 3.8.0 version. Helps only `val installKotlinterPrePushHook by tasks.creating(InstallPrePushHookTask::class)`. We use `kotlin-android`
