### ISSUE TITLE
QUESTION: Shouldn't formatKotlin run after lintKotlin if ignoreFailures = true?

### ISSUE THREAD

**Issue by obvionaoe** [jeremymailen/kotlinter-gradle#143]
I've added kotlinter to my build script and I expected that 2 new tasks (lintKotlin and formatKotlin) would run after the rest!

But only lintKotlin runs... formatKotlin only runs if I trigger it manually with `./gradlew formatKotlin`

Am I doing something wrong?

**Comment by jeremymailen** [comment]
This is the expected functionality. `lintKotlin` is automatically added to the standard `check` lifecycle, but `formatKotlin` is left as a standalone task so that people can incorporate it according to their preference, whether that's on file save, or pre-commit, etc.

When running `./gradlew check` in CI it would be unexpected for files to be modified by the build system. The `ignoreFailures` simply prevents failure of the build for any team that wish to report on their lint issues, but allow builds to continue. I don't know if anyone takes advantage of this workflow as it seems like most teams prefer to take a firm stance on no check ins without proper formatting.

An "auto-fix" workflow is something we've been discussing lately however and we're considering implementing that in a pre-commit hook.

**Comment by obvionaoe** [comment]
I'm not very familiar with the hooks mechanism, how would that work? and how does the installKotlinterPrePushHook work?

**Comment by jeremymailen** [comment]
If you are using `git` for your project, it installs a hook that runs whenever you are about to *push* a branch remotely. `installKotlinterPrePushHook` today just fails the push if anything failed lint and tries to format any files it can, leaving the user to review and commit the fixes. We've discussed a new hook that would run every time you *committed* files locally, automatically formatting anything that needed it and silently including them in your commit. This would be something like an "auto-fix" workflow.

**Comment by jeremymailen** [comment]
For reference, this is what the pre-push look looks like when installed
```bash
#!/bin/sh

##### KOTLINTER HOOK START #####
GRADLEW=/path/to/myproject/gradlew
$GRADLEW lintKotlin

status=$?
if [ "$status" != 0 ] ; then
    echo 1>&2 "\nlintKotlin found problems, running formatKotlin; commit the result and re-push"
    $GRADLEW formatKotlin
    exit 1
fi
##### KOTLINTER HOOK END #####
```

**Comment by obvionaoe** [comment]
The auto-fix workflow would probably be the one more useful to my project! But for now how would I go about installing that pre-push hook for the project? so that other developers also have access to it as well?

**Comment by jeremymailen** [comment]
I might need to know more details about your project and the workflow you want everyone to use.

In professional projects I've worked on, there's often a `setup.sh` or `make setup` in the project that does some one-time dependency setup. Something like that could run `./gradlew installKotlinterPrePushHook` as part of its commands. Of course all of this assumes your team is using `git` for version control.

**Comment by obvionaoe** [comment]
We are using git, and I think I could add that setup.sh script! but I was looking through your src folder and I found this [GitHookTasks](https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/GitHookTasks.kt) isn't the pre-commit already implemented?

**Comment by jeremymailen** [comment]
We almost implemented it, then realized we need to do more work if it was doing to also silently add files to the commit being made.

**Comment by obvionaoe** [comment]
Oh, is there any way I can help? Since I would be using this feature I would be very glad to help expedite the process!

**Comment by jeremymailen** [comment]
Input and help always useful. Discussion here:
https://github.com/jeremymailen/kotlinter-gradle/pull/137#pullrequestreview-427739206

**Comment by obvionaoe** [comment]
Took a look, but I really don't know how to help... by the way I tried using the pre-push hook but I think it didn't work because in the build the lintKotlin task had problems but when I pushed it ran a build but the pushed files were without formatting and so were the local ones!

**Comment by obvionaoe** [comment]
Hey, thanks for the help but I found the best way was to make the local Gradle build depend on formatting and exclude those tasks from the CI build! One of the reasons I went with this is because IntelliJ is kinda unstable with git hooks, as it crashed a lot...

**Comment by jeremymailen** [comment]
👍
