### ISSUE TITLE
Plugin errors if .editorconfig is absent on gradle versions < 5.4.0

### ISSUE THREAD

**Issue by pedroql** [jeremymailen/kotlinter-gradle#148]
If you are using this plugin with an old version of gradle and you don't have a file `.editorconfig` in the root project, then you will see this weird message:

```
$ ./gradlew tasks
Could not create task ':formatKotlinMain'.
path may not be null or empty string. path='null'
```

(Even without trying to run task of the plugin.)

After some investigation I understood the problem was related with the file `.editorconfig` not being present (although, to the best of my knowledge, that's not a requirement).

It seems that this is a bug with gradle that was fixed in this commit:

https://github.com/gradle/gradle/commit/796504edffe1d4b8c085cbb37edbbc848d2c9a73

Which implies that if you don't have the file there, you need to use gradle 5.4.0 or newer.

I'm reporting this for:

1. If someone else sees a similar message, hopefully they can find this solution (upgrade gradle version or create the file)
1. You might want to update the ReadMe stating this limitation, or make a workaround/check in the code

**Comment by jeremymailen** [comment]
Thank you for the detailed report and investigation as you made my job very easy 😄 !

Given that gradle is a major version up from 5.4.0 now, should we try to compensate or could we leave this issue behind as a note for anyone who might trip over the issue. Our advice would be to upgrade gradle.

**Comment by jeremymailen** [comment]
Will be resolved in next release as we don't configure editorconfig path anymore (delegating that to ktlint)
