### ISSUE TITLE
Parameter for formatKotlin task to fail instead of trying to fix problems

### ISSUE THREAD

**Issue by pedroql** [jeremymailen/kotlinter-gradle#149]
Hi,

I want to run `formatKotlin` in CI. For this reason, I don't want the task to attempt to fix the code. If there are issues, I want the task to fail and the PR can't be merged until the issues are addressed by the developer. 

I know we have the option to setup the pre-push hook but this is to prevent the case of someone who didn't install that to submit breaking code to the repo.

Also, I don't like the idea of CI creating a new commit when the task is able to solve the issues. That's why I would like it to fail the task instead.

After reading the docs and browsing the source code, I believe this functionality is not yet possible.

**Comment by jeremymailen** [comment]
As I understand it the `lintKotlin` task should do exactly what you describe: fails if there are any lint issues and produces a report; does not attempt to fix anything.

The plugin automatically makes `lintKotlin` a dependency of the `check` stage. So in the projects I've worked on we typically do `gradle check` in CI and that will require all the lint checks and tests to pass for the pull request.

Let me know if this meets your needs.

**Comment by pedroql** [comment]
My scenario is related with formatting, not linting. Let's say someone submits a PR with 3 consecutive new lines which breaks the formatting rules. 

By running `formatKotlin`, the plugin would be able to delete the extra new lines and would pass the PR while the PR still contains these extra lines there (because the plugin doesn't commit the changes).

What I would like to have is a configurable option to say that instead of applying fixes just fail the task if any problem is found.

**Comment by jeremymailen** [comment]
Ah, maybe the terminology is a bit confusing, but `lintKotlin` validates the exact same formatting rules that `formatKotlin` does. So they are equivalent in enforcement, but take a different action when they find an issue (fail vs fix).

I realize this terminology clashes a bit, especially for Android developers, where the term "lint" often refers to semantic level checks to validate the code is written properly. Despite their names `ktlint` and this `kotlinter` plugin that wraps it is only concerned with code style and format.

**Comment by pedroql** [comment]
> I realize this terminology clashes a bit, especially for Android developers

You completely caught me there!

OK, then the functionality is there I just didn't understand the naming. Thank you for your help!
