### ISSUE TITLE
Fails to configure in git worktree

### ISSUE THREAD

**Issue by ephemient** [jeremymailen/kotlinter-gradle#161]
```
$ git worktree add ../branch
$ cd ../branch
$ ./gradlew
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create task ':installKotlinterPrePushHook'.
> Could not create task of type 'InstallPrePushHookTask'.
   > Not a directory
```

as https://github.com/jeremymailen/kotlinter-gradle/blob/4f6944a0ca8eba4573467c24c52515b5303d5772/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/GitHookTasks.kt#L40 tries to `mkdirs()` immediately upon configuration, but in a [git worktree](https://git-scm.com/docs/git-worktree), `.git` is actually a text file that points to the shared GIT_DIR.

**Comment by jeremymailen** [comment]
Thanks for the report. I wasn't familiar with the worktree feature. Is there a good programmatic way to determine you are in a worktree and resolve the correct git dir?

Is it a reasonable workaround to change to the parent git dir and install the hook from there? I assume hooks installed there apply to all worktrees.

**Comment by ephemient** [comment]
Yes, hooks apply to all git worktrees. You can use `git rev-parse --git-dir` or `git rev-parse --absolute-git-dir` to find the .git directory. Which is probably a better thing to do anyway, there's no guarantee the Gradle root project is the same as the Git root directory.

**Comment by ephemient** [comment]
Come to think of it, in the case that Gradle root != Git root, there might not be a good way to install the hook anyway. (For example, a repository like https://github.com/googlesamples/android-vulkan-tutorials - a repo-wide hook wouldn't know which subdirectories to run in.) So perhaps task should make sure it does nothing if `git rev-parse --show-prefix` or `git rev-parse --show-cdup` from cwd=`rootProject.projectDir` are successful and empty. Otherwise, creating a mostly-empty `.git` directory within a subdirectory (or outside of a Git working tree) is just going to confuse git and other tools.

**Comment by jeremymailen** [comment]
It will still work ok, I did test it out.

The hook script is merely invoking `gradle lintKotlin`, which in the context of your current worktree will resolve all the sourceSets of files to check using gradle's configuration. None of that logic depends on the location of the hook script.

Try installing the hook from your parent git directory and see if the hook operates as expected for you when you are working in another worktree.

**Comment by jeremymailen** [comment]
Added a note in the readme, please let me know if you run into any other issues using the hook!

**Comment by ephemient** [comment]
The problem isn't installing the hook - I wasn't even trying to run that task. The problem is that Gradle can't even configure the project due to the task trying to mkdirs at creation time.

**Comment by jeremymailen** [comment]
I see, my apologies for not seeing that detail. Not sure why I didn't run into that problem testing it.
Will investigate and fix.

**Comment by jeremymailen** [comment]
Ok, actually fixed this time. Release 3.1.1.
