### ISSUE TITLE
Certain Imports Removed by Formatter

### ISSUE THREAD

**Issue by bellini-ea** [jeremymailen/kotlinter-gradle#165]
In a kotlin project, using 3.2.0 of this plugin, the following import is totally removed by the formatter cause build failures due to the deleted line.  I have mitigated this so we can continue to use the formatter however it is not ideal.

```
import org.mockito.Mockito.`when` as mockWhen
```

![image](https://user-images.githubusercontent.com/46908694/95131373-c9b7be00-0712-11eb-842e-daef50aaa07d.png)

**Comment by jeremymailen** [comment]
Thank you for reporting. It appears to be a bug in the underlying ktlint engine: https://github.com/pinterest/ktlint/issues/937

I will watch the issue and incorporate a fix when available.

**Comment by jeremymailen** [comment]
You may already be mitigating it this way, but a workaround is to suppress ktlint for that line of code:
https://github.com/pinterest/ktlint#how-do-i-suppress-an-error-for-a-lineblockfile

In this case I think it's
```kotlin
/* ktlint-disable no-unused-imports */
import org.mockito.Mockito.`when` as mockWhen
/* ktlint-enable no-unused-imports */
```

**Comment by jeremymailen** [comment]
Should be fixed in the latest
