### ISSUE TITLE
Git-hook not formatting

### ISSUE THREAD

**Issue by alexKatona** [jeremymailen/kotlinter-gradle#170]
Hello there,
I started using the plugin, its working good so far, decided to also use the git hooks but it seems like its not catching the fail and not starting the formater. using gradle 6.7.1.

Also have a question, is it possible to merge all the reports into one file ? would be pretty convinient to show the html report on CI for example. Using multi module project.

<img width="846" alt="Screenshot 2020-12-21 at 14 50 15" src="https://user-images.githubusercontent.com/14858450/102786015-284e1900-439f-11eb-92ea-8d22e23cec17.png">
<img width="1730" alt="Screenshot 2020-12-21 at 14 49 56" src="https://user-images.githubusercontent.com/14858450/102786020-2a17dc80-439f-11eb-96c4-bdc3a2630c9b.png">
<img width="389" alt="Screenshot 2020-12-21 at 14 48 49" src="https://user-images.githubusercontent.com/14858450/102786026-2b490980-439f-11eb-9bba-934a15a478c2.png">

**Comment by jeremymailen** [comment]
Thanks for your patience during the holidays and thank you for reporting the issue.

I haven't been able to reproduce the issue with the hook script not invoking a format. If you do these commands outside that script:
```shell
gradle lintKotlin
echo $?
```
Do you get `1`?

**Comment by jeremymailen** [comment]
Re the report consolidation, what CI do you use and how does it select which reports to show?

The current scheme was designed to matching the out of the box gradle checkstyle plugin -- a task and report for each source set, by default build quits on first failure. It's been a while but I remember Jenkins used to know how to surface those reports.

**Comment by Rinat-Suleimanov** [comment]
Same for me, the pre-push hook failed with the ./gradlew lintKotlin and thats it. 

When run just 
```
gradle lintKotlin
echo $?
```
 I've got 1

**Comment by Rinat-Suleimanov** [comment]
There is the pre-push hook console output
```
[ktlint 664a5b4] linter test commit
 1 file changed, 1 insertion(+), 1 deletion(-)
10:03:35.634: [backend-core] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/ktlint:ktlint
> Task :generateJooqClasses UP-TO-DATE
> Task :lintKotlinMain FAILED
~/backend/core/models/CommonResponse.kt:1:1: Lint error > [final-newline] File must end with a newline (\n)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':lintKotlinMain'.
> lintKotlinMain sources failed lint check
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date
error: failed to push some refs to 'git@github.com:/intentomatic/backend-core.git'
```

**Comment by jeremymailen** [comment]
I imagine this problem is fixed, the scripting has changed a bit
```
##### KOTLINTER HOOK START #####
##### KOTLINTER 3.4.4 #####
GRADLEW=/path/to/gradlew
if ! $GRADLEW lintKotlin ; then
    echo 1>&2 "\nlintKotlin found problems, running formatKotlin; commit the result and re-push"
    $GRADLEW formatKotlin
    exit 1
fi
```

Will close, but please reopen if still happening.
