### ISSUE TITLE
[Question] How install git hook?

### ISSUE THREAD

**Issue by ispite** [jeremymailen/kotlinter-gradle#180]
Hello, I didn't get how I should install git hook
I try to add in build.gradle (project)
```
task check {
    dependsOn "installKotlinterPrePushHook"
}
```
but receive an error
```
Could not determine the dependencies of task ':check'.
> Task with path 'installKotlinterPrePushHook' not found in root project 'CodeConventions_hw8_4_new'.
```

and how I can change it on preCommit?

**Comment by jeremymailen** [comment]
It could be perhaps your root project does not `apply plugin: 'org.jmailen.kotlinter'`?

Once it does (and the kotlin plugin as well to supply `check`) this should work
```groovy
check {
    dependsOn "installKotlinterPrePushHook"
}
```
