### ISSUE TITLE
[Question] How to add custom rules via plugins block?

### ISSUE THREAD

**Issue by a-ivanov** [jeremymailen/kotlinter-gradle#186]
Hello everyone!

If I install the kotlinter via Gradle `plugins` block

```
plugins {
    id("org.jmailen.kotlinter") version "<version>"
}
```

is it possible to add my custom rules (e.g. from another jar)?

I know that `buildscript` block option is described in Readme, but afaik this is not compatible with `plugins` block.

Thanks.

**Comment by jeremymailen** [comment]
Correct, I believe gradle requires you to use the `buildscript` block when you need to modify the classpath of the build and that's where you will need to include your custom rules in the classpath. Hope this helps.
