### ISSUE TITLE
3.4.1 Seems to require Java 15, becomes incompatible with lower Java versions

### ISSUE THREAD

**Issue by mateuszkwiecinski** [jeremymailen/kotlinter-gradle#189]
I don't see what in the diff caused the incompatibility https://github.com/jeremymailen/kotlinter-gradle/compare/3.4.0...3.4.1, but when trying to use recent plugin version in an environment with lower java version, it fails with a message similar to:

```
> Could not resolve all artifacts for configuration ':buildSrc:classpath'.
   > Could not resolve org.jmailen.gradle:kotlinter-gradle:3.4.1.
     Required by:
         project :buildSrc > org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin:3.4.1
      > No matching variant of org.jmailen.gradle:kotlinter-gradle:3.4.1 was found. The consumer was configured to find a runtime of a library compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.0' but:
          - Variant 'apiElements' capability org.jmailen.gradle:kotlinter-gradle:3.4.1 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 15 and the consumer needed a runtime of a component compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0')
          - Variant 'runtimeElements' capability org.jmailen.gradle:kotlinter-gradle:3.4.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 15 and the consumer needed a component compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0')
```
The build passes on Java 15. [Sample failed run](https://github.com/usefulness/project-starter/actions/runs/791534478)

I'm quite sure that's not an expected behavior change so I'm reporting an issue here.

btw. the new Gradle Toolchains feature might be helpful here https://docs.gradle.org/current/userguide/toolchains.html

**Comment by jeremymailen** [comment]
Good catch. Definitely not intentional. Bytecode target should be 8. It may indeed be a side effect of upgrading to gradle 7 and not declaring the toolchain?

**Comment by mateuszkwiecinski** [comment]
> It may indeed be a side effect of upgrading to gradle 7 and not declaring the toolchain?

I don't think so, there is no _default_ toolchain which would change the compatibility (or at least I'm not aware of such behavior). and btw. they were introduced in Gradle 6.8

My guess would be local environment of the machine which created the release artifact. If I'm not mistaken, by default the jar compatibility depends on the java version that builds it, and Gradle Toolchains only simplify managing that.
I couldn't find the CI run that triggered the release, but I'd first make sure it didn't have Java 15 installed and set as a default.

I don't understand that part of Gradle well enough to understand what precisely happened here and unfortunately I don't have time right now to investigate it more thoroughly, but I can share my config that produces a Java 8 compatible artifact, built with [Java 15](https://github.com/usefulness/issuechecker/blob/master/.github/workflows/publish_release.yml#L28): https://github.com/usefulness/issuechecker/blob/master/build.gradle#L12

**Comment by jeremymailen** [comment]
Thank you, this is helpful. I guess now jar compatibility requires more than just bytecode -- declaring which JDK apis are required by the component. Will try to fix tomorrow.

**Comment by jeremymailen** [comment]
Ok, should be fixed now, give 3.4.2 a try.

**Comment by mateuszkwiecinski** [comment]
Thanks! I can confirm 3.4.2 works on Java 11, and fails on Java 8 👍 

You wrote:
>1.8 is pretty old and unsupported now.

😬 
I'll share that Java 8 seems to be still a standard in Android world 😞 Google announced Android Gradle Plugin 7.0 will require Java 11, but that's still in a distant future (at least half a year before it reaches stable version). 
Despite it is possible to build an Android project with latest Java version, I'm quite sure at least half of the Android community still uses Java 8 (I think I saw a poll on reddit, but still, _citation needed_). 
Requiring Java 11, at this moment of AGP release cycle, may be problematic for large number of Android Project which aren't ready for Java update.
(It doesn't affect me personally, but I thought it might be worth sharing)

**Comment by jeremymailen** [comment]
Yes, you are right of course. I need to be more in tune with Android since most Kotlin users are there -- I'm a server dev!

Let me do another incremental bump back to 8.

**Comment by jeremymailen** [comment]
Ok, 3.4.3 it is!

**Comment by mateuszkwiecinski** [comment]
Thanks! 
I can confirm it works, even on Java 8 🚀
