### ISSUE TITLE
Unused import not reported

### ISSUE THREAD

**Issue by schmist** [jeremymailen/kotlinter-gradle#19]
Given the following configuration:

https://gist.github.com/schmist/c4c205bde4bb2b085e71688c3ef10d83

`import java.util.Date` in `Main.kt` is not recognized as an unused import as long as it is used in class `L`. Renaming class `L` to `N` (so that it appears alphabetically after file `Main.kt`) fixes the issue.

**Comment by jeremymailen** [comment]
Thanks for the report, I'll look into it tonight.

**Comment by jeremymailen** [comment]
Thank you for reporting the bug. You've discovered a subtle issue which probably resulted in a number of missed lint errors. I'll push a fixed 1.3.2 in a moment.

**Comment by schmist** [comment]
Thanks for the fix. Great work!
