### ISSUE TITLE
Update documentation, promote using modern Gradle APIs

### ISSUE THREAD

**Issue by mateuszkwiecinski** [jeremymailen/kotlinter-gradle#195]
I've noticed current documentation presents sample snippets that rely on Gradle APIs which result in a less performant consumer build or ar simply less readable. 

I'll list couple of them:
1. 
``` kotlin
repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
```
can be replaced with
```
repositories.gradlePluginPortal()
```

2. Accroding to the [docs](https://docs.gradle.org/current/userguide/plugins.html#sec:constrained_syntax) the promoted way of applying the plugin is via `plugins` block. 
So instead of a
```
buildscript {
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath("org.jmailen.gradle:kotlinter-gradle:3.4.3")
    }
}
```
there should be
```
plugins {
    id "org.jmailen.kotlinter" version "3.4.3" apply false
}
```
3. 
```
check {
    dependsOn "installKotlinterPrePushHook"
}
```
called in Groovy configures `check` task eagerly. The modern approach is to have a:
```
tasks.named("check) {
    dependsOn "installKotlinterPrePushHook"
}
(this is acutally the most common one)
```
4. Custom tasks are registered by
```
tasks.create<LintTask>("ktLint") {
```
which is again, against the [recommended way](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html)

I'm creating an issue, just in case when someone feels inspired to go through the documentation and refresh all usages that would need such 😃

**Comment by jeremymailen** [comment]
Yes, agree. It would be nice to update the docs with the modern best practice.
