### ISSUE TITLE
Missing javadocs on maven publication

### ISSUE THREAD

**Issue by mateuszkwiecinski** [jeremymailen/kotlinter-gradle#196]
When looking at published artifacts:
```
total 296
-rw-r--r--  1 user  staff   17143 May  2 23:06 kotlinter-gradle-3.4.3-sources.jar
-rw-r--r--  1 user  staff  118805 May  2 23:06 kotlinter-gradle-3.4.3.jar
-rw-r--r--  1 user  staff    3794 May  2 23:06 kotlinter-gradle-3.4.3.module
-rw-r--r--  1 user  staff    3006 May  2 23:06 kotlinter-gradle-3.4.3.pom
```
it seems like what's beeing published doesn't actually meet what's being configured. 

Project defines `javadocJar` which seems to be a part of project `artifacts`, but AFAICS it doesn't get included in the maven publication. 
Seeing it contains a lot of custom configuration I'd recommend to switch to a simpler publication config, which would rely on publishing `java` component instead of setting all coordinates and artifacts manually. 

Unless not publishing javadoc jar is an expected behavior?

**Comment by jeremymailen** [comment]
Honestly it's accidental. Project probably doesn't need javadoc given there's not much and people use this as a gradle plugin not a library. Will remove.
