### ISSUE TITLE
Pre-push hook shows an error

### ISSUE THREAD

**Issue by nkgcp** [jeremymailen/kotlinter-gradle#205]
In Windows 10, you can see hook install task generate hook looks like this.

```sh
#!/bin/sh
set -e
##### KOTLINTER HOOK START #####
##### KOTLINTER 3.4.4 #####
GRADLEW=C:\Users\rlcks\workspace\freelec\gradlew.bat
if ! $GRADLEW lintKotlin ; then
    echo 1>&2 "\nlintKotlin found problems, running formatKotlin; commit the result and re-push"
    $GRADLEW formatKotlin
    exit 1
fi
##### KOTLINTER HOOK END #####
```

And this shows error with message below.

```
.git/hooks/pre-push: line 6: C:Usersrlcksworkspacefreelecgradlew.bat: command not found
\nlintKotlin found problems, running formatKotlin; commit the result and re-push
.git/hooks/pre-push: line 8: C:Usersrlcksworkspacefreelecgradlew.bat: command not found
error: failed to push some refs to 'https://github.com/nkgcp/freelec.git'
```

It seems like `\` in the hook file is recognized as escape character. Changing `\` to `\\` or `/` makes it works fine.

**Comment by jeremymailen** [comment]
Thank you for the error report @nkgcp! Will get it fixed soon.

**Comment by rvplauborg** [comment]
Whats the status on this - we also ran into it and it would be nice to avoid it for newcomers to the project :-)

**Comment by jeremymailen** [comment]
Sorry it's slipped through the cracks.
The fastest way would be for someone to submit a PR -- especially someone who works in a windows environment and can quickly verify the fix.
Otherwise I will try to get to it.

**Comment by rvplauborg** [comment]
Nothing to be sorry for! I can maybe do a PR monday.

**Comment by rvplauborg** [comment]
Nothing to be sorry about. I am not sure how to verify a fix. I think a possible solution could be altering `gradlew.path` to `gradlew.invariantSeparatorsPath` in the `gradleCommand` val. But not sure how to verify it.

**Comment by jeremymailen** [comment]
> Nothing to be sorry about. I am not sure how to verify a fix. I think a possible solution could be altering `gradlew.path` to `gradlew.invariantSeparatorsPath` in the `gradleCommand` val of `GitHookTask.kt`. But not sure how to verify it.

On your pull request branch you can bump version, publish to maven local, and then in your test project put `mavenLocal()` first in the repo list and pull in the version of kotlinter built by your PR. At least that's what I usually do.

**Comment by rvplauborg** [comment]
Hmm.. Cant seem to make it work.

```

plugins {
   ...
    id("org.jmailen.kotlinter") version "3.5.0-test" // my test version
}


    repositories {
        mavenLocal()
        mavenCentral()
    }
```
Cannot find it. But I can find it in my ~.m2/repository folder.

**Comment by jeremymailen** [comment]
Or the instructions for multi-module in the readme will work:

```kotlin
buildscript {
    repositories {
        mavenLocal()
        ...
    }
    dependencies {
        classpath("org.jmailen.gradle:kotlinter-gradle:3.5.0-test")
    }
}

apply(plugin = "org.jmailen.kotlinter")
```

**Comment by bespaltovyj** [comment]
@rvplauborg thanks for your idea for solution this problem.
I have issued a pull request along with it. Sorry, if you wanted to do it yourself. 

https://github.com/jeremymailen/kotlinter-gradle/pull/218
