### ISSUE TITLE
Multiple reporters?

### ISSUE THREAD

**Issue by aochsner** [jeremymailen/kotlinter-gradle#22]
Doesn't seem possible but is possible via `ktlint`  Any chance support could be added?

**Comment by jeremymailen** [comment]
Should be reasonable to implement. Do you have a suggestion for what the configuration might look like? Perhaps something like?
```Groovy
kotlinter {
    ignoreFailures = false
    indentSize = 4
    reporters = ['checkstyle', 'json']
}
```

**Comment by aochsner** [comment]
Yeah I think that makes a lot of sense to me!

**Comment by jeremymailen** [comment]
Add in 1.5.0

**Comment by aochsner** [comment]
Awesome!  Thanks!
