### ISSUE TITLE
Enabling "sarif" formatter causes `lintKotlin` task to become useless

### ISSUE THREAD

**Issue by ephemient** [jeremymailen/kotlinter-gradle#221]
```kotlin
tasks.lintKotlin {
    reports.put("sarif", file("ktlint.sarif"))
}
```

`./gradlew lintKotlin` now succeeds, writing empty reports, without checking any ktlint issues.

**Comment by jeremymailen** [comment]
Thank you for letting me know! We hadn't added support for that reporter yet, but adding it now.

**Comment by jeremymailen** [comment]
Give 3.6.0 a try, now included
