### ISSUE TITLE
How to configure indentation for the case like this

### ISSUE THREAD

**Issue by oradkovsky** [jeremymailen/kotlinter-gradle#225]
Hello!

I'm using 3.3.0 version with Android Studio 2020.3.1 patch 3.

Kotlin linter complains about this code:

![image](https://user-images.githubusercontent.com/9694896/140278000-919df6c7-24a6-4afe-9015-c4450eb149ad.png)

`Unexpected indentation (16) (should be 12)`

What is proper way to configure indentation in such example?

**Comment by jeremymailen** [comment]
KLint supports a few different options for configuring indents, kotlinter-gradle will support all the values you might place in .editorconfig https://github.com/pinterest/ktlint#editorconfig

It's hard to tell from your screenshot what the context of those string literals is? Is it in line with the android [style guide](https://developer.android.com/kotlin/style-guide)? Should it be a triple quote """ literal?

**Comment by oradkovsky** [comment]
Thanks for great lib. Will keep on investigating. Even https://ktlint-demo.herokuapp.com/ behaves the same with the same code snippet.
