### ISSUE TITLE
Doesn't work in kts

### ISSUE THREAD

**Issue by Goooler** [jeremymailen/kotlinter-gradle#231]
You can check out [this branch](https://github.com/Goooler/kotlinter-gradle/tree/kts) for tests, I added an extra blank but `lintKotlin` or `formatKotlin` don't work out of the box, this bug was continued for a long time.

**Comment by jeremymailen** [comment]
Kotlinter automatically adds lint and format tasks only for supported gradle plugins. In those cases it uses registered source sets.

If a project wanted to lint `.kts` files which are not part of a known source set, it would need to configure a custom task as described here: https://github.com/jeremymailen/kotlinter-gradle#custom-tasks

**Comment by Goooler** [comment]
Should we add this point in README ?

**Comment by jeremymailen** [comment]
Seems like it's implied? The documentation leads in describing how tasks are automatically created for supported Gradle plugins. We could have a task on this project that lints it's own build script in the spirit of adopting own capabilities.

**Comment by Goooler** [comment]
As I use ktlint-gradle before kotlinter, it support kts by default, so I assume ktlinter support kts too after migration, but not in actuality.

**Comment by jeremymailen** [comment]
It supports linting kts files. The main difference in expectation is it will not automatically configure tasks to lint any kts files found in the directory, only those that are in source sets. There's a reasonable case to be made that if a project uses kts build scripts these are well known configured sources it ought to pick up and include in a task such as `lintBuildscripts`.

**Comment by Goooler** [comment]
I know I know. Just like you said, maybe it's implied, need to add a description?
