### ISSUE TITLE
LintTask doesn't rerun when editorconfig changes

### ISSUE THREAD

**Issue by joshmsamuels** [jeremymailen/kotlinter-gradle#233]
I have been trying to configure kotlinter with my `.editorconfig` and I was having problems getting `kotlinter` to respect my rules since it looks like the lint task is being persistently cached.

Every time I make a `.editorconfig` change and run `build`, the change gets picked up by kotlinter, however, every time I run `LintTask`, whether right after a gradle clean or with `./gradlew clean lintKotlin` it says there are no issues even though there are lint errors since I changed the `editorconfig` rules.

As a temporary work-around, https://github.com/jeremymailen/kotlinter-gradle/issues/112#issuecomment-521733398 helped me prevent the `ListTask` from caching when I run `./gradlew lintKotlin --rerun-tasks`. 

This issue makes me lose confidence in the `prePushHook` or other linter automation since I will never know if the linter truly should have succeeded, so are there any permanent solutions to this issue?

**Comment by mateuszkwiecinski** [comment]
It seems like the plugin should declare `.editorconfig`s picked by `ktlint` as each task's `@Input` (similairly as `ktlint-gradle` does - [link](https://github.com/JLLeitschuh/ktlint-gradle/blob/f8f78dc3163fe96e78aafcc3ebd62b8ab0ff7045/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/BaseKtLintCheckTask.kt#L60)). 
I wonder if it can be done in a smart way using one of the ktlint classes, to make sure the new task input is kept in sync with ktlint 🤔  I'm looking at [EditorConfigLoader](https://github.com/pinterest/ktlint/blob/3866e09dd36f5559f3a7c9f8c1d080f3211d095a/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoader.kt#L54) but I don't quite get where do they search for `.editorconfig` files location 🤔 

@joshmsamuels As a temp workaround I can suggest you to add your `.editorconfig` file as kotlinter tasks input
```
    val editorconfigFile = rootProject.file(".editorconfig") // or whatever the file location is.
    tasks.withType<LintTask> {
        inputs.file(editorconfigFile).withPathSensitivity(PathSensitivity.RELATIVE)
    }
```

**Comment by joshmsamuels** [comment]
That worked 🎉  Thank you so much!

Is there a way to define this for all kotlinter tasks instead of just the lint task? It looks like I have to copy the same function for the `FormatTask` as well

**Comment by mateuszkwiecinski** [comment]
I think we can keep the issue open, as that's still a bug in the plugin and should be fixed at some point 👀 

>Is there a way to define this for all kotlinter tasks instead of just the lint task?

I don't think you have to define such patch for `FormatKotlin` task. It is never considered _UP-TO-DATE_ - [source](https://github.com/jeremymailen/kotlinter-gradle/blob/124e8e017cc9469915003fdcb052047015aa2072/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/FormatTask.kt#L25)m so it will always be executed against most recent `.editorConfig`* 👀  

* - Unless you use [Configuration Cache](https://docs.gradle.org/current/userguide/configuration_cache.html), but I'm guessing you don't

**Comment by jeremymailen** [comment]
Yes, as @mateuszkwiecinski points out, the gap here is that editorconfig is not currently an Input to the LintTask, so you have to force a rerun if you change the rules there. Incremental build should behave correctly in all other cases. I changed  the issue title accordingly.

It would be nice to resolve the path to editorconfig and use it as an input in the plugin. Currently the resolution and reading of editorconfig is delegated to the underlying ktlint library.

Yes, FormatTask does not attempt to be incremental. If memory serves, doing so would make it unpredictable because sometimes it changes the input files themselves and sometimes it does not.

**Comment by joshmsamuels** [comment]
Thanks for the clarification! I also have a shared `exclude` between the two tasks so if there is a common place I could define that, it would great!
