### ISSUE TITLE
Conflict with IntelliJ IDEA autoformat

### ISSUE THREAD

**Issue by edeak** [jeremymailen/kotlinter-gradle#234]
Can you help me figuring out what and how to configure to get rid of the following conflict?

```kotlin
// linter format
class MyCliktCommand : CliktCommand() {
    private val myOption 
        by option("--myOption")
        .int()
        .default(1)
}

// IDEA Autoformat
class MyCliktCommand : CliktCommand() {
    private val myOption 
        by option("--myOption")
            .int()
            .default(1)
}
```

**Comment by mateuszkwiecinski** [comment]
@edeak If I'm not mistaken you have to add `indent_size = x` to your `.editorconfig` file. See this example: https://github.com/jeremymailen/kotlinter-gradle/blob/124e8e017cc9469915003fdcb052047015aa2072/.editorconfig#L3

**Comment by edeak** [comment]
will post this issue there instead.

**Comment by jeremymailen** [comment]
Thanks for jumping in as always @mateuszkwiecinski 
I believe `indentSize = 4` is the default however. I wonder if ktlint has a bug on indentation following a `by`?
