### ISSUE TITLE
`lintKotlin` stops as soon as one sourceset fails

### ISSUE THREAD

**Issue by AlvaroBrey** [jeremymailen/kotlinter-gradle#268]
For reporting purposes I'd like to run `lintKotlin` over all sourcesets, but it will stop as soon as any sourceset fails and skip remaining sourcesets.

**Comment by mateuszkwiecinski** [comment]
Hey @AlvaroBrey, have you tried using `--continue` flag (`./gradlew lintKotlin --continue`)? This will result in all tasks being invoked

**Comment by AlvaroBrey** [comment]
> Hey @AlvaroBrey, have you tried using `--continue` flag (`./gradlew lintKotlin --continue`)? This will result in all tasks being invoked - [documentation](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continue_build_on_failure)

Thanks! wasn't aware of that option. It works.
