### ISSUE TITLE
lintKotlin report errors and but formatKotlin does not fix it

### ISSUE THREAD

**Issue by hantsy** [jeremymailen/kotlinter-gradle#271]
Update the new 3.11.1, I found there are some errors reported like this in the Git Hooks. 

```
Lint error > [annotation] Multiple annotations should not be placed on the same line as the annotated construct
```

But I have run `./gradlew formatKotlin` before git push.

**Comment by jeremymailen** [comment]
I don't believe that every issue ktlint can report it's also capable of fixing. Some issues must be manually remediated.

**Comment by hantsy** [comment]
How to disable this rule to keep it compatible with last version?

**Comment by jeremymailen** [comment]
Rules can be disabled through the [configuration](https://github.com/jeremymailen/kotlinter-gradle#configuration) `disabledRules` property or using the .editorconfig (see ktlint docs).
