### ISSUE TITLE
Changing the output directory of the LintTask

### ISSUE THREAD

**Issue by StylianosGakis** [jeremymailen/kotlinter-gradle#274]
I was looking into using [this GitHub Action](https://github.com/yutailang0119/action-ktlint) in order to take the errors output by the reporters and have them be annotated in my PR.
Thing is, I used to be able to do that in a mono-module setup where I knew where the output of the reporters were, but now with a multi-module setup the LintTask is generating a lot of files all in separate build files one for each module and I can't quite get this all to work out.
I was wondering if there is any way I can configure that task to output everything at one spot where this GH Action can pickup and use instead.

[Here](https://github.com/HedvigInsurance/android/blob/c53bbe06eff702bebfadcffba2aaaf8e076a8197/build-logic/convention/src/main/java/KtlintConventionPlugin.kt#L9-L41) is my current configuration, but since `KotlinterExtension` does not take in any such config I don't know if this would be possible. I was using the other gradle plugin before (ktlint-gradle), which allowed me to have [this kind](https://github.com/HedvigInsurance/android/blob/209108c7ddb1c5b3fd27035082586d4fc56d8da3/build-logic/convention/src/main/java/KtlintConventionPlugin.kt#L34-L38) of configuration before, but since that one seems to now be abandoned and after reading [this](https://kotlinlang.slack.com/archives/CKS3XG0LS/p1661630223962909?thread_ts=1661381921.902119&cid=CKS3XG0LS) discussion I thought I'd switch over to kotlinter.

There probably will be more people like me who will be asking similar question so it'd be nice to have an answer on the feasibility of this.

**Comment by mateuszkwiecinski** [comment]
>I was wondering if there is any way I can configure that task to output everything at one spot where this GH Action can pickup and use instead.

Have you tried overriding task's `reports` property? I mean something like:
```kotlin
tasks.withType<LintTask>().configureEach {
    reports.set(mapOf("checkstyle" to rootDir.resolve("reports/${project.path}.xml")))
}
```
which would save all reports under `{root}/reports/{unique-subproject-name}.xml}` using `checkstyle` reporter (you can alter either the report format or output name). Is that something you were looking for?

**Comment by StylianosGakis** [comment]
Yeap that was it, I was trying to see if I can edit this in `KotlinterExtension` which is why I never figured I could edit the `LintTask` directly 🙌
This [PR](https://github.com/HedvigInsurance/android/pull/1209) does do exactly what I was looking for. All the reporters output on that common file, thanks a lot!
