### ISSUE TITLE
Kotlinter doesn't match cli behavior for multiline-if-else rule

### ISSUE THREAD

**Issue by andrewg** [jeremymailen/kotlinter-gradle#276]
ktlint: 0.47.1
kotlinter: 3.11.1
standard rules except disabled_rules `import-ordering` and `filename` in both build.gradle and .editorconfig (have the same issue as https://github.com/jeremymailen/kotlinter-gradle/issues/262)

It's in the standard rules but kotlinter doesn't seem to be failing on it: https://github.com/pinterest/ktlint/blob/0.47.1/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/MultiLineIfElseRule.kt

```
❯ ./gradlew buildEnvironment | grep kotlinter
\--- org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin:3.11.1
     \--- org.jmailen.gradle:kotlinter-gradle:3.11.1

❯ ktlint --version
0.47.1

❯ ./gradlew lintKotlin

BUILD SUCCESSFUL in 3s
2 actionable tasks: 2 executed

❯ ktlint
15:51:53.350 [main] INFO com.pinterest.ktlint.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
*****.kt:77:16: Missing { ... } (multiline-if-else)
*****.kt:78:16: Missing { ... } (multiline-if-else)
...
```

**Comment by mateuszkwiecinski** [comment]
`3.11.1` uses ktlint version `0.46.0`. The [upgrade](https://github.com/jeremymailen/kotlinter-gradle/pull/275) to `0.47.1` was merged yesterday, but hasn't been released yet. 
If you want to try `0.47.1` with kotlinter `3.11.1` you may want to visit [Custom ktlint version](https://github.com/jeremymailen/kotlinter-gradle#custom-ktlint-version) section in Readme 👀 It'll call ktlint using deprecated apis, but it _should_ produce the same results as your CLI

**Comment by andrewg** [comment]
Oh my bad, I had just done a search and saw it was at at 0.47.1 but didn't check against the tag. Thanks for the info!
