### ISSUE TITLE
Execution optimizations have been disabled for task ':lintKotlinMain'

### ISSUE THREAD

**Issue by hoanghun** [jeremymailen/kotlinter-gradle#281]
I get a warning:

> Execution optimizations have been disabled for task ':lintKotlinMain' to ensure correctness due to the following reasons:
>   - Gradle detected a problem with the following location: '<>'. Reason: Task ':lintKotlinMain' uses this output of task ':generateContractWrappers' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#implicit_dependency for more details about this problem.

Versions:
> Gradle 7.5
> id("org.jmailen.kotlinter") version "3.11.1"

Found this mentioned in different Ktlint gradle plugin [issue](https://github.com/JLLeitschuh/ktlint-gradle/issues/457).

**Comment by mateuszkwiecinski** [comment]
I failed to reproduce the issue and AFAICS all files accessed by kotlinter are declared as its inputs 👀 Would you mind sharing a repro project?

**Comment by hoanghun** [comment]
@mateuszkwiecinski https://github.com/hoanghun/kotlinter--281-repro-project/tree/main here is the link to the repro project.

```

> Task :lintKotlinMain
Execution optimizations have been disabled for task ':lintKotlinMain' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '~/open-source/ktlinter-example/build/generated/sources/web3j/main/java'. Reason: Task ':lintKotlinMain' uses this output of task ':generateContractWrappers' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

```

**Comment by mateuszkwiecinski** [comment]
I checked `main` branch, updated project config to use latest version of Gradle and kotlinter, I invoked `./gradlew check --warning-mode all --rerun-tasks --no-configuration-cache --scan` and I see only a few of deprecation warnings coming from `id("org.web3j")"`. 
Build scan: https://scans.gradle.com/s/xw7hiostud5yc/console-log?page=1#L3 

I'd suggest you to either exclude generated files (https://github.com/jeremymailen/kotlinter-gradle/issues/242) or declare the  dependency to run kotlinter tasks _after_ `generateContractWrappers ` using [mustRunAfter](https://docs.gradle.org/7.4.2/dsl/org.gradle.api.Task.html#org.gradle.api.Task:mustRunAfter(java.lang.Object[])) call. 

Hope this helps :)

**Comment by hoanghun** [comment]
Did you try `./gradlew build` though? With the `check` flag there is no warning as you mentioned, but with the `build`, I can reproduce the issue.

**Comment by mateuszkwiecinski** [comment]
I did now, and it does indeed reproduce the issue 👍  My suggestions are still the same. Most probably you don't want to run ktlint over generated files :)

**Comment by hoanghun** [comment]
Yeah, you are right. It makes no sense whatsoever to run Ktlint over generated files. Shouldn't this be the default though?

**Comment by mateuszkwiecinski** [comment]
I'm not aware of any way to distinguish generated files from the non-generated ones. If you look at the plugin responsible for the conflict: https://github.com/web3j/web3j-gradle-plugin/blob/5ca6d20074c76171a52c004164f7a3f44a48cc22/src/main/java/org/web3j/gradle/plugin/Web3jPlugin.java#L98 - they add their sources to _regular_ sourceSet 👀 
I don't understand what the web3j plugin does, but ideally these generated classes could be a separate compilation unit (i.e. separate module, added as regular `project` dependency. Or they could register their own task 🤷)
Whatever happens, I personally don't see anything that can improved here, on the kotlinter side 👀

**Comment by jeremymailen** [comment]
Yes, kotlinter configuration can be customized to exclude these files. It would be better if code generating plugins could implement separate, properly annotated source sets we could easily identify for exclusion.

**Comment by mateuszkwiecinski** [comment]
Given there is nothing we can really improve on the plugin side, I'm going to close the issue for now.
