### ISSUE TITLE
installKotlinterPrePushHook not working using 3.8.0

### ISSUE THREAD

**Issue by AlexKuz13** [jeremymailen/kotlinter-gradle#283]
> Pretty sure that's the reason. I updated the instructions here https://github.com/jeremymailen/kotlinter-gradle#git-hooks and also pushed 2.4.1 which will add this task even if there isn't a kotlin source code plugin present on the root project.

The same problem in 3.8.0 version. Helps only `val installKotlinterPrePushHook by tasks.creating(InstallPrePushHookTask::class)`. We use `kotlin-android`

_Originally posted by @AlexKuz13 in https://github.com/jeremymailen/kotlinter-gradle/issues/142#issuecomment-1250804896_

**Comment by mateuszkwiecinski** [comment]
The latest version is `3.12.0` can you verify the issue still persists? If not - can you share a repro project?

**Comment by mateuszkwiecinski** [comment]
I'll close the issue for now - please let us know if you can reproduce the issue on the latest version (a repro project woul be much appreciated 🙏 )
