### ISSUE TITLE
JCIFS referenced in LICENSE

### ISSUE THREAD

**Issue by matthewlmcclure** [jeremymailen/kotlinter-gradle#287]
I found the [LGPL included in LICENSE for JCIFS](https://github.com/jeremymailen/kotlinter-gradle/blob/9f200573e54cde1fb0e55b06fa03f85ca27a1630/LICENSE#L458), but I didn't find any reference to JCIFS in the source code. Is JCIFS actually used?

**Comment by mateuszkwiecinski** [comment]
I don't know what is it for and not sure if that's helpful, but looking at the structure of `LICENSE` file it's _under_ "Gradle Subcomponents" header:  https://github.com/jeremymailen/kotlinter-gradle/blob/a539a4db0512e3a4278645f644e6f33f54c18299/LICENSE#L206 

Your observations are correct and `JCIFS` isn't used by Kotlinter's source code, so does it have to be mentioned in Kotlinter's licence? I don't know 😬 
Looking around: [Gradle itself](https://docs.gradle.org/current/userguide/licenses.html) is licensed under the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), and they don't seem to mention `JCIFS` 👀 

I'll ping @jeremymailen who should have more context here and I hope will know if there is anything actionable here 👀

**Comment by jeremymailen** [comment]
Yeah, we don't use JCIFS. My memory is failing me right now, but I think I started this GitHub project with an Apache 2 license template. Not sure how JCIFS got in there, will remove.
