### ISSUE TITLE
Accessing task using named() instead of withType()

### ISSUE THREAD

**Issue by aaulia** [jeremymailen/kotlinter-gradle#297]
If I want to configure the task reports using `tasks.named(...)` instead of `tasks.withType(LintTask)`, since I want to split my gradle files into several smaller one. I've hit a couple of issues.

1. What is the name the tasks use? `lintKotlin`?
2. I've tried `lintKotlin` but gradle kept complaining that it doesn't have `reports`
3. A bit OOTP, but gradle also complaint that it can't resolve `import org.jmailen.gradle.kotlinter.tasks.LintTask`. The build is fine though, so I guess it's false positive on their side, maybe.

**Comment by mateuszkwiecinski** [comment]
>>If I want to configure the task reports using tasks.named(...) instead of tasks.withType(LintTask), since I want to split my gradle files into several smaller one.

I'm not sure if I got the reasoning between configuring `withType()` vs `named()` 🤔 `withType` allows you to configure all tasks with a given type for a given project. `named` allows you to alter configuration for a specific task. 
This plugin registers one `LintTask` per each source set in your project. So there might be `lintKotlinMain`, `lintKotlinIosMain`, `lintKotlinTest`, `lintKotlinTestFixtures`, `lintKotlinDebug`, depending on which plugins you apply to your project. ([Readme](https://github.com/jeremymailen/kotlinter-gradle#tasks)). 

Can you elaborate on what's wrong with `tasks.withType(LintTask)`? How does this prevent you from splitting your configuration into smaller chunks? And what is your end goal? What's your use case for configuring tasks directly?

As I didn't fully get what you're asking about, I'll try to answer your points directly

>1. What is the name the tasks use? lintKotlin?

`lintKotlin` is a lifecycle task that groups all source-set specific tasks. You can run `./gradlew :projectName:lintKotlin -m` to view all source-set tasks for a given project

> 2. I've tried lintKotlin but gradle kept complaining that it doesn't have reports

`lintKotlin` is only a lifecycle task, it doesn't perform any action. You have to configure specific `LintTask`s which has `report` property, as shown in projects Readme

> 3. but gradle also complaint that it can't resolve import org.jmailen.gradle.kotlinter.tasks.LintTask. The build is fine though, so I guess it's false positive on their side, maybe.

That sounds like an IDE issue - have you tried re-syncing it? If the issue persists, but the project compiles fine - please do report that issue to IDE maintainers.

**Comment by aaulia** [comment]
Actually I just want to split my `build.gradle` into smaller files with specific settings block (`detekt`, `ktlint`, `linter`, `android`, etc). Basically kind of like convention plugin but without actually making a plugin. Unfortunately `import` and `plugins` block cannot be used in separate gradle file, so referencing the Task Class using generic like `withType()` is not supported (CMIIW). In `detekt` case, fortunately I can modify the report path using `tasks.named()` instead of using type resolution way (`tasks.withType()`). So I figure, why not using the same approach for `kotlinter`.

Thank you for your response, I will try it again, but this isn't urgent or anything, just curious.

As for question no. 3. Yes, by "their" side, I mean the IDE. I've resync it, but haven't tried invalidating it. Maybe that will solve it, who knows :).

**Comment by aaulia** [comment]
@mateuszkwiecinski Just wanted to let you know, using "lintKotlinMain" (one of the many lintKotlin task), works. Thank you.
