### ISSUE TITLE
[Request] Support Kotlin/JS

### ISSUE THREAD

**Issue by krzema12** [jeremymailen/kotlinter-gradle#299]
The plugin doesn't add its task for Kotlin/JS projects, see:
https://github.com/jeremymailen/kotlinter-gradle/blob/4b8d58e1646b935cab555bbda1114adeeac6997d/src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterPlugin.kt#L19-L23

Related Slack thread: https://kotlinlang.slack.com/archives/CKS3XG0LS/p1669819315336379

Is it by design? If no, could you add support for it or would you be open for contribution?

**Comment by jeremymailen** [comment]
Yes, we're just missing it and we can add.
