### ISSUE TITLE
add custom ktlint RuleSets from within a project's module?

### ISSUE THREAD

**Issue by kenyee** [jeremymailen/kotlinter-gradle#309]
There is documentation on how to do this for JAR files as well as maven artifacts, but is it possible to use a project's module that contains the files for custom rules?

e.g.., I want to do:
```
buildscript {
    dependencies {
        classpath(project(":libs:custom-ktlint-rules"))
    }
}
```

**Comment by jeremymailen** [comment]
If I understand correctly your request, that's being worked on.
See https://github.com/jeremymailen/kotlinter-gradle/issues/34

Closing as duplicate.
