### ISSUE TITLE
Multiple sourceSets

### ISSUE THREAD

**Issue by SylvainHocq** [jeremymailen/kotlinter-gradle#31]
Hello, 

i have a project with 2 sourceSet directory "java" and "newarchy".
I do it like this : 

`sourceSets {
        main.java.srcDirs += 'src/main/newarchy'
    }`

The "newarchy" contains kotlin files and some java files.

But when i run ` ./gradlew lintKotlin`  , it check only file in "java" directory

How can i configure my project to check another directory ?

Thanks.

**Comment by jeremymailen** [comment]
Ok, we can do it manually although the plugin is supposed to get the Kotlin SourceSets by querying the `kotlin`, `kotlin-jvm`, or `kotlin-android` plugins. It might not work in every case 🤔.

Can you try something to help me troubleshoot?
`gradle -d clean lintKotlin | grep "linting:"`
And let me know if it finds some or all of your sources?

If the automatically created lint/format tasks do not find your source, you can create additional ones as described in the https://github.com/jeremymailen/kotlinter-gradle/blob/master/README.md.

Example:
```groovy
import org.jmailen.gradle.kotlinter.tasks.LintTask

task lintNewarchy(type: LintTask, group: 'verification') {
    source files('src')
    reports = [
            'plain': file('build/lint-report.txt'),
            'json': file('build/lint-report.json')
    ]
}

lintKotlin.dependOn lintNewarchy
```

**Comment by SylvainHocq** [comment]
Hi,
the command line ` gradle -d clean lintKotlin | grep "linting:"` respond nothing
But the custom Task works.
I modify a little the scrip because there are few mistake and the import don't works : 


` 
task lintNewArchy(type: org.jmailen.gradle.kotlinter.tasks.LintTask, group: 'verification') {
    source files('src/main/new-archy')
    reports = [
            'plain': file('build/lint-report.txt'),
            'json' : file('build/lint-report.json')
    ]
    indentSize = 4
    ignoreFailures = false
    continuationIndentSize = 4
}

task formatNewArchy(type: org.jmailen.gradle.kotlinter.tasks.FormatTask, group: 'formatting') {
    source files('src/main/new-archy')
    report = file('build/format-report.txt')
    indentSize = 4
    continuationIndentSize = 4
}

lintKotlin.dependsOn lintNewArchy
`

**Comment by jeremymailen** [comment]
Ok, cool. Which gradle plugins do you apply? Is this an Android or JVM project?
