### ISSUE TITLE
[Help] Task 'installKotlinterPrePushHook' not found in root project.

### ISSUE THREAD

**Issue by Ridje** [jeremymailen/kotlinter-gradle#311]
Hello.

**Description**
I am trying to execute installKotlinterPrePushHook automatically when someone is starting build.
Android Studio is saying build.gradle.kts:29:7: Unresolved reference: check
Generally the problem is gradle can't see installKotlinterPrePushHook task at all.

**Versions**
Gradle's version: 7.3.3
kotlinter-gradle version: 3.13.0

**Root's build.gradle.kts**
```
plugins {
    id("org.jmailen.kotlinter") version "3.13.0" apply false
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:${Versions.gradle}")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0")
        classpath("androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.navigation}")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}

tasks.register("clean", Delete::class) {
    delete(rootProject.buildDir)
}

tasks.check {
    dependsOn("installKotlinterPrePushHook")
}
```
<details>
  <summary>Screenshot</summary>
<img width="951" alt="image" src="https://user-images.githubusercontent.com/4568712/216762349-68149cd8-eb51-40ff-8c4a-50d23d460ce8.png">
</details>

**Module's build.gradle.kts plugins section**
```
plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("kapt")
    id("androidx.navigation.safeargs.kotlin")
    id("kotlin-parcelize")
    id("kotlin-android")
    id("org.jmailen.kotlinter")
}
```
**Gradle sync and ./gradlew installKotlinterPrePushHook**
```
* What went wrong:
Script compilation errors:

  Line 29: tasks.check {
                 ^ Unresolved reference: check

  Line 30:     dependsOn("installKotlinterPrePushHook")
               ^ Unresolved reference: dependsOn
```
```
./gradlew installKotlinterPrePushHook

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installKotlinterPrePushHook' not found in root project ''.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
6 actionable tasks: 6 up-to-date
```

**Comment by junerver** [comment]
> Hello.
> 
> **Description** I am trying to execute installKotlinterPrePushHook automatically when someone is starting build. Android Studio is saying build.gradle.kts:29:7: Unresolved reference: check Generally the problem is gradle can't see installKotlinterPrePushHook task at all.
> 
> **Versions** Gradle's version: 7.3.3 kotlinter-gradle version: 3.13.0
> 
> **Root's build.gradle.kts**
> 
> ```
> plugins {
>     id("org.jmailen.kotlinter") version "3.13.0" apply false
> }
> 
> buildscript {
>     repositories {
>         google()
>         mavenCentral()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:${Versions.gradle}")
>         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0")
>         classpath("androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.navigation}")
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         maven { url = uri("https://jitpack.io") }
>     }
> }
> 
> tasks.register("clean", Delete::class) {
>     delete(rootProject.buildDir)
> }
> 
> tasks.check {
>     dependsOn("installKotlinterPrePushHook")
> }
> ```
> 
> Screenshot
> **Module's build.gradle.kts plugins section**
> 
> ```
> plugins {
>     id("com.android.application")
>     kotlin("android")
>     kotlin("kapt")
>     id("androidx.navigation.safeargs.kotlin")
>     id("kotlin-parcelize")
>     id("kotlin-android")
>     id("org.jmailen.kotlinter")
> }
> ```
> 
> **Gradle sync and ./gradlew installKotlinterPrePushHook**
> 
> ```
> * What went wrong:
> Script compilation errors:
> 
>   Line 29: tasks.check {
>                  ^ Unresolved reference: check
> 
>   Line 30:     dependsOn("installKotlinterPrePushHook")
>                ^ Unresolved reference: dependsOn
> ```
> 
> ```
> ./gradlew installKotlinterPrePushHook
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'installKotlinterPrePushHook' not found in root project ''.
> 
> * Try:
> > Run gradlew tasks to get a list of available tasks.
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> 6 actionable tasks: 6 up-to-date
> ```

Hello, I have encountered the same problem, how should I solve it, thank you

**Comment by ryanholden8** [comment]
Same issue, confused why this was closed?

**Comment by Ridje** [comment]
> Same issue, confused why this was closed?

I closed it because I spent 3 days trying to make different plugins work for my needs. And I feel like it was just a waste of time. If you're not proficient with Gradle, plugins can make things even harder to understand. For my purposes, I simply created a pre-commit hook that installs on every build run if it hasn't been installed yet.
