### ISSUE TITLE
ReporterType marked as internal necessary?

### ISSUE THREAD

**Issue by StylianosGakis** [jeremymailen/kotlinter-gradle#313]
In version 3.11 I was using the ReporterType type in order to easily reference the reporter I was interested in by doing this https://github.com/HedvigInsurance/android/blob/ee08122b0534cc51c185bd55d99742776ccb6dfe/build-logic/convention/src/main/kotlin/KtlintConventionPlugin.kt#L22
Now it's marked as internal and I have to use a String, which is a tiny bit more prone to error. I mean of course in my case I will just replace it with the "checkstyle" string, but I thought it was a convenient way to do this without fearing that if the name changes or something like that in the future I will get an error in my build since it won't be able to reference the `org.jmailen.gradle.kotlinter.support.ReporterType` anymore.
Was this marked as internal for a specific purpose, or just due to not wanting to make any public API guarantees on it?

**Comment by jeremymailen** [comment]
I don't think we're intentionally trying to hide it, was probably more code hygiene given it wasn't used in the plugin outside that scope.

**Comment by StylianosGakis** [comment]
Yeah I understand. Do you think my use-case makes sense for it to be public again in some future release? I reverted to using the string directly for now, but I am gonna admit I did like having the type there. Now it looks like [this](https://github.com/HedvigInsurance/android/blob/99bfb6cd7604f14fb6446ce1e4ad144d28cd4454/build-logic/convention/src/main/kotlin/KtlintConventionPlugin.kt#L19) which I feel like is a downgrade.
No problem if you don't feel like changing it back though, just sharing my use case.
