### ISSUE TITLE
Remove trailing comma

### ISSUE THREAD

**Issue by hantsy** [jeremymailen/kotlinter-gradle#318]
Upgraded to the latest version 3.14.0, when formatting the codes, it adds the `trailing comma` back by default.

I have tried to add the following .editorconfig according to the Ktlint docs, it does not work(all data classes, fun parameters still add commas).

```editorconfig
[*.{kt,kts}]
ktlint_code_style=official
ij_kotlin_allow_trailing_comma_on_call_site=false
ktlint_standard_trailing-comma-on-call-site=false
ij_kotlin_allow_trailing_comma=false
ktlint_standard_trailing-comma-on-declaration-site=false
```

**Comment by jeremymailen** [comment]
This got me too the first time, but see [here](https://pinterest.github.io/ktlint/rules/configuration-ktlint/#disabled-rules).
The value to use is `disabled` rather that false.

**Comment by hantsy** [comment]
@jeremymailen Which one use `disabled`, the example config in the doc https://pinterest.github.io/ktlint/rules/configuration-ktlint/#trailing-comma-on-call-site uses a `false` there.

**Comment by hantsy** [comment]
Thanks @jeremymailen 

```editorconfig
[*.{kt,kts}]
ktlint_code_style=official
ij_kotlin_allow_trailing_comma_on_call_site=false
ktlint_standard_trailing-comma-on-call-site=disabled
ij_kotlin_allow_trailing_comma=false
ktlint_standard_trailing-comma-on-declaration-site=disabled
```

It works.

Another format I can not find in Ktlint config.  I want to keep the ";" in the enum class. 

```kotlin

enum class Status{
    PENDING,
    COMPLETED;
}
```

Upgraded to the new 3.14.0, it removes **;** in all files.

**Comment by hantsy** [comment]
The `ktlint_standard_no-semi = disabled` does not work.
