### ISSUE TITLE
Compatibility matrix is out of date

### ISSUE THREAD

**Issue by rsmith20** [jeremymailen/kotlinter-gradle#320]
The compatibility matrix specifies 3.11+ as compatible with min gradle version 7.0, but 3.14 is compiled using Kotlin 1.8 and gradle 7.5 expects Kotlin 1.6.

**Comment by jeremymailen** [comment]
So you are saying the new row needs to be 3.14+ compatible with gradle 7.6+?

**Comment by mateuszkwiecinski** [comment]
I'd suggest not updating the compatibility in readme, but rather revert [these two](https://github.com/jeremymailen/kotlinter-gradle/blob/5c890e84bcc1b19bbaf92f5b50a9505c4b3e3807/build.gradle.kts#L101-L102) properties back to 1.4. 
```
kotlinOptions {
    apiVersion = "1.4"
    languageVersion = "1.4"
}
```
This should restore plugin compatibility with lower versions. Gradle enforces Kotlin version in runtime, so these settings effectively are not respected and only cause incompatibilities 🤷 

The runtime with Kotlin 1.8 is available only on Gradle 8: https://docs.gradle.org/current/userguide/compatibility.html#kotlin

**Comment by jeremymailen** [comment]
I bumped it because IntelliJ indicated that 1.4 was deprecated.
Is there significant user base still using a version of gradle that old?

**Comment by jeremymailen** [comment]
I think the compatibility matrix is up-to-date, but please reopen if there are still issue.
