### ISSUE TITLE
.editorconfig file per module?

### ISSUE THREAD

**Issue by jasonab** [jeremymailen/kotlinter-gradle#321]
I'm not sure what the expected behavior is here - I have a `.editorconfig` file in my root, but the submodules do not respect the rules in that file. If I copy that file into each submodule, then kotlinter/ktlint respects those rules, but this seems like a bad pattern. Do I need to configure kotlinter somehow to use my root `.editorconfig` or am I supposed to copy it?

**Comment by jeremymailen** [comment]
It should honor an .editorconfig file in the root directory and editorconfig files further down the tree can modify that behavior as per the spec for editorconfig.

Largely this behavior is implemented in the underlying ktlint library via ec4j.
Is there anything unusual about your project? Is kotlinter-gradle applied to the root project or just the submodules?

**Comment by jasonab** [comment]
Ok, I think I figured it out - the gradle daemon is caching the `.editorconfig` file, and not respecting changes to it. I'm not sure where that's coming from, but I can reproduce it regularly. This is with gradle 7.6.1.

**Comment by jeremymailen** [comment]
Ok, yeah, the .editorconfig not being re-evaluated is an issue that's come up, although I thought we fixed it in https://github.com/jeremymailen/kotlinter-gradle/releases/tag/3.12.0.
Which version are you on?

**Comment by jasonab** [comment]
Looks like that was using 3.12

**Comment by jeremymailen** [comment]
The fix was basically to track the .editorconfig files as inputs to the build to correctly re-run tasks when they changed.
So one possibility is a really long lived gradle daemon with some cruft.
The other possibility is we didn't fix the bug like we thought.

**Comment by jeremymailen** [comment]
Yeah, I'll close this for now and open a bug for editorconfig staleness.
