### ISSUE TITLE
Library is now coupled to editor config

### ISSUE THREAD

**Issue by CharlieTap** [jeremymailen/kotlinter-gradle#325]
I don't actually have an editor config file and it would be great if I didn't have to add one. I was previously configuring rules using the disabled rules extension but now I'm forced to either stay on .13 or adopt .editor_config in my repository.

**Comment by jeremymailen** [comment]
It's a design decision made by ktlint
https://pinterest.github.io/ktlint/install/cli/#rule-configuration-editorconfig
So the interface to the engine just allows for reliably setting which rule sets to load and not individual rule settings. I hear where you are coming from, but it's kinda the state of things and adding an editorconfig is not a bad idea. It will make sure whatever code editor you use agrees with ktlint and they don't fight with each other.

**Comment by CharlieTap** [comment]
Fair I'll bite the bullet 👍🏼
