### ISSUE TITLE
Compatibility with ktlint 1.0.0

### ISSUE THREAD

**Issue by jakoss** [jeremymailen/kotlinter-gradle#342]
After ktlint went to 1.0.0 we can see new artifacts (https://github.com/pinterest/ktlint/releases/tag/1.0.0). So Kotlinter needs another minor bump to adjust to that i think :)

**Comment by jeremymailen** [comment]
Yes, we'll need to update the plugin. Been a bit busy lately.
Sometimes on these big releases I like to wait for the first bugfix patch to come in.

**Comment by jakoss** [comment]
No worries, I'm not rushing. Thanks for all the work 😁

**Comment by jeremymailen** [comment]
Completed with [4.0.0 release](https://github.com/jeremymailen/kotlinter-gradle/releases/tag/4.0.0).
Thanks for your patience everyone!
