### ISSUE TITLE
Task formatKotlin should fail build if it cannot fix all lint errors

### ISSUE THREAD

**Issue by acreddy9** [jeremymailen/kotlinter-gradle#347]
This issue is the inverse of issue [#335](https://github.com/jeremymailen/kotlinter-gradle/issues/335).

It is slightly misleading when the `formatKotlin` task build succeeds with unfixed lint errors. This can be solved by adding an optional configuration so users can choose whether the `formatKotlin` task build succeeds (default) or fails when it is unable to autoformat all lint errors detected. The configuration should be overrided by the `ignoreFailures` configuration, such that if `ignoreFailures` is set to `true` then the build will always succeed. We actually have this solution ready and can make a PR, but wanted to open this issue first to provide an explanation and receive any initial feedback :)

**Comment by juliakispert** [comment]
We would love any feedback on the PR or issue. Thank you in advance!

**Comment by jeremymailen** [comment]
Sorry about the delay. It's been extraordinarily busy this part month. I do plan to get the pending changes reviewed and a new version out, but it might be a few days before I can get to it.

**Comment by jeremymailen** [comment]
Will incorporate into 4.1.0.
