### ISSUE TITLE
Upgrade to ktlint 1.0.1

### ISSUE THREAD

**Issue by dessalines** [jeremymailen/kotlinter-gradle#350]
Currently, I can't use this with jetpack compose because of this issue:

https://github.com/pinterest/ktlint/issues/2333

edit: #348

**Comment by rmarquis** [comment]
A new release would be welcome, but In the meantime you can override the ktlint version used by kotlinter plugin. Look at the [Custom ktlint version](https://github.com/jeremymailen/kotlinter-gradle#custom-ktlint-version) section of the README.

**Comment by jeremymailen** [comment]
Upgrade is out [here](https://github.com/jeremymailen/kotlinter-gradle/releases/tag/4.0.1)
