### ISSUE TITLE
Allow disabling of [standard:discouraged-comment-location]

### ISSUE THREAD

**Issue by thejeff77** [jeremymailen/kotlinter-gradle#351]
The new v4 cannot auto-fix, nor will support/allow disabling the rule for this:

[standard:discouraged-comment-location] A comment in a 'value_parameter_list' is only allowed when placed on a separate line

Suffice to say, its annoying as s***.

Kindly allow an option to disable this in config. When adding to `.editorconfig`, it doesn't work and gives a warning it is not supported:

![Screenshot 2023-11-09 at 7 09 00 AM](https://github.com/jeremymailen/kotlinter-gradle/assets/8584457/686139b2-db15-4eec-a827-034c24734e1c)

**Comment by mateuszkwiecinski** [comment]
According to https://pinterest.github.io/ktlint/1.0.1/rules/configuration-ktlint/#disabled-rules a proper syntax is:
```yaml
ktlint_standard_discouraged-comment-location = disabled
```
and not `= off`

(make sure you kill the gradle daemon (`./gradlew --stop`), to ensure .editorconfig changes are properly picked up)

**Comment by thejeff77** [comment]
Thanks for the quick feedback! 

Seem to be getting this after changing it and re-running:
```

java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:if-else-wrapping)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
```

**Comment by jeremymailen** [comment]
Thanks for the assist @mateuszkwiecinski!

**Comment by thejeff77** [comment]
@jeremymailen did you see that I responded and the suggestion didn't work before you closed this?

**Comment by jeremymailen** [comment]
@thejeff77 this is a different problem. ktlint is seeing your specification, but certain rules are dependent on others.
See issue discussion here: https://github.com/pinterest/ktlint/issues/2338

**Comment by thejeff77** [comment]
@jeremymailen I read that, I'm not sure what the resolution is. Do you have any recommendations?

I'd argue that if a [solution ](https://github.com/jeremymailen/kotlinter-gradle/issues/351#issuecomment-1803925559)doesn't solve the issue and in-fact breaks the tool, it isn't a full solution..

**Comment by thejeff77** [comment]
Here's my full config if it helps, and the linting is broken:

```
[*.{kt,kts}]
max_line_length = off
ktlint_standard_discouraged-comment-location = disabled
ktlint_standard_if-else-wrapping = disabled
```

**Comment by jeremymailen** [comment]
I think the solution is only specifying how to correctly get the setting to "take" and doesn't speak to which other rules are required.
Neither I nor @mateuszkwiecinski are committers on https://github.com/pinterest/ktlint and that's the logic that's causing you trouble.

**Comment by thejeff77** [comment]
@jeremymailen ok thanks.. I'll post over there. That's helpful. Appreciate the quick replies. I really need to figure out how to turn this off in a way that actually works.

**Comment by jeremymailen** [comment]
I found that setting `ktlint_code_style` to `intellij_idea` went a long way towards making the lint enforcement acceptable.
Like you, I don't find this idea of dependent lint rules to be user friendly and can a become a blocker for adoption.
