### ISSUE TITLE
Support for ktlint arg android

### ISSUE THREAD

**Issue by DavidCorrado** [jeremymailen/kotlinter-gradle#354]
Using an older version of ktlint and kotlinter because of the intellij plugin for ktlint we are using.  So we are using 3.14.0 kotlinter and ktlint 0.48.2.   Is it possible to send the ktlint option to run it in android mode.  Basically its ktlint -a.  So I want to run the project with android ktlint rules and just want to confirm whether or not that version supports android ktlint rules.  I could not find a way to send that mode.  Just confirming I am not missing something.

**Comment by jeremymailen** [comment]
I believe what you want to do is set this in your .editorconfig:
```
[*.{kt,kts}]
ktlint_code_style = android_studio
```
See [here](https://pinterest.github.io/ktlint/0.50.0/rules/code-styles/).

I believe the -a is [deprecated](https://pinterest.github.io/ktlint/0.50.0/install/cli/#miscellaneous-flags-and-commands) even on that version.

**Comment by davidcorradowell** [comment]
That worked!  Thanks appreciate your support.  BTW on my old version it was ktlint_code_style = android
