### ISSUE TITLE
Attempting to set custom ktlint version causes error

### ISSUE THREAD

**Issue by xenomachina** [jeremymailen/kotlinter-gradle#36]
The README says:

> If you need to use a different version of ktlint you can override the dependency.
> 
> ```
> buildscript {
>     configurations.classpath {
>         resolutionStrategy { force 'com.github.shyiko:ktlint:0.11.1' }
>     }
> }
> ```

When I add this:

```
configurations.classpath {
    resolutionStrategy { force 'com.github.shyiko:ktlint:0.15.0' }
}
```

...to the buildscript section of my build.gradle it fails:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Operation is not supported for read-only collection
```

**Comment by jeremymailen** [comment]
Are you sure it isn't due to something else?
I can get this to work ok:
```Groovy
buildscript {
    buildscript {
        configurations.classpath {
            resolutionStrategy { force 'com.github.shyiko:ktlint:0.14.0' }
        }
    }

    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.2'
    }
}

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.2.0'
    id 'org.jmailen.kotlinter' version '1.7.0'
    id 'application'
    id 'eclipse'
    id 'idea'
}

apply plugin: 'org.junit.platform.gradle.plugin'
```

**Comment by jeremymailen** [comment]
Oh I see, if I swap this to kotlinter `1.6.0` and ktlint `0.15.0` I get
```
Caused by: java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
        at kotlin.collections.EmptyList.addAll(Collections.kt)
        at org.jetbrains.kotlin.gradle.dsl.OptionsUtilKt.copyFreeCompilerArgsToArgs(optionsUtil.kt:24)
        at org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptionsImpl.updateArguments$kotlin_gradle_plugin(KotlinJvmOptionsImpl.kt:26)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.setupCompilerArgs(Tasks.kt:305)
```
And then if I switch to kotlin `1.2.20` it works.

So this due to:
### Compatibility
Kotlinter 1.7.0 and later compatible with Kotlin Gradle plugins 1.2.20+

**Comment by xenomachina** [comment]
Thanks!

I wish this gave a better error message. "Operation is not supported for read-only collection" is about as opaque as it gets.

**Comment by jeremymailen** [comment]
Yeah, gradle doesn't surface more detail until you add the flag `gladly --stacktrace <task>` and even then I suppose it's hard to interpret. I happened to already know that ktlint uses some internal APIs for the kotlin compiler that can lead to version incompatibilities.
