### ISSUE TITLE
4.5.0 Build Failure Class org.jetbrains.kotlin.cli.common.CompilerSystemProperties does not have member field 'org.jetbrains.kotlin.cli.common.CompilerSystemProperties COMPILE_INCREMENTAL_WITH_ARTIFACT_TRANSFORM'

### ISSUE THREAD

**Issue by thejeff77** [jeremymailen/kotlinter-gradle#419]
Class org.jetbrains.kotlin.cli.common.CompilerSystemProperties does not have member field 'org.jetbrains.kotlin.cli.common.CompilerSystemProperties COMPILE_INCREMENTAL_WITH_ARTIFACT_TRANSFORM'

Anyone seen this?

Get it on upgrading to 4.5.0 from 4.4.1

**Comment by jeremymailen** [comment]
Which version of Kotlin are you using? It's likely a version compatibility issue, especially if you are on 2.1.0.

**Comment by jeremymailen** [comment]
Try [5.0.0](https://github.com/jeremymailen/kotlinter-gradle/releases/tag/5.0.0), should be fixed there. Report back if not.
