### ISSUE TITLE
kotlinter 5.0.0 on mvnrepository

### ISSUE THREAD

**Issue by mshearer-hubspot** [jeremymailen/kotlinter-gradle#427]
Hey,

Is it intentional that kotlinter 5.0.0+ isn't published on mvnrepository.  
We need it for our internal tooling, so wondering if we need to work around that.

cheers

**Comment by jeremymailen** [comment]
Did you find what you need? We publish to gradle, e.g.
https://plugins.gradle.org/m2/org/jmailen/kotlinter/org.jmailen.kotlinter.gradle.plugin/5.0.1/
