### ISSUE TITLE
Plugin doesn't seem to take account changes to source set after plugin is applied

### ISSUE THREAD

**Issue by mikeholler** [jeremymailen/kotlinter-gradle#53]
I'm using this plugin like this:

```
apply plugin: "com.android.application"
apply plugin: "kotlin-android"
apply plugin: "org.jmailen.kotlinter"

...
android {
    ...
    sourceSets {
        main {
            java.srcDirs += "src/main/kotlin"
        }
        test {
            java.srcDirs += "src/test/kotlin"
        }
        androidTest {
            java.srcDirs += "src/androidTest/kotlin"
        }
    }
}
```

The problem is kotlinter seems to resolve the source sets and collect the files right away, in the apply step. Changes made later have no effect. I'd like to use "src/group/kotlin" directories since these are pure kotlin projects.

What I'd like to see is the source file discovery deferred until task run time. I think it'd be fine if this plugin still searched for source sets on apply for purpose of creating the tasks, but I think each task should get a list of files from the app at runtime, rather than plugin apply time.

This is a fine plugin all around and I'd like to keep using it. I spent about an hour looking at how to hack a solution in, but it required a decent amount of refactoring and I don't have the time at the moment. I may pick it up in a few weeks when I have some spare time, but for now I'm leaving this issue open to put it on the radar and perhaps see if someone has a quick fix for it.

**Comment by autonomousapps** [comment]
I know this isn't solving your problem in the exact way you would like, but my suggestion is to remove the Kotlin-specific sourceSets. There is no value-added there, in my opinion. It is totally valid to have `.kt` files in Java sourceSets, and it will simplify things for you and any devs on your team. Just imagine if you want to convert a Java file to a Kotlin file using the ctrl-alt-shift-K. You'd then have to manually move the file to another directory as a second step.

Food for thought!

**Comment by mikeholler** [comment]
That's all fine and good, but the official documentation for use of the Kotlin Gradle plugin suggests, and for pure Kotlin _adds_ a kotlin source directory. If it's an officially recommended place to put things, this use case should be supported.

https://kotlinlang.org/docs/reference/using-gradle.html

Also there are plenty of valid use cases to add a directory to a source set beyond just this example.

**Comment by mikeholler** [comment]
Here's the direct anchor to the Android recommendation:

https://kotlinlang.org/docs/reference/using-gradle.html#android-studio

**Comment by autonomousapps** [comment]
I agree fully on your second point, and I did not know about the first!

**Comment by mikeholler** [comment]
For anyone else who needs it in the meantime, here's my terribly hacky solution, which I apply after messing with SourceSets:

```
project.plugins.withId("org.jmailen.kotlinter") {
    ['main', 'test', 'androidTest'].collect { groupName ->
        ['formatKotlin', 'lintKotlin'].collect { taskName ->
            "$taskName${groupName.capitalize()}"
        }
    }.flatten().each {
        project.tasks.findByName(it).source(fileTree('src/main/kotlin'))
    }
}
```

**Comment by jeremymailen** [comment]
Thank you for the detailed info @mikeholler. This is definitely intended to work and I agree complete the use case should be supported. It's a bug I wasn't aware of but probably should have uncovered already.

Let me look into what the right thing to do is. Surely it's possible because I think plugins like `checkstyle` support sourceSet customization. As we know, understanding the Gradle build lifecycle is a journey not a destination.

Another work around in the meantime would be to create https://github.com/jeremymailen/kotlinter-gradle#custom-tasks for each of your sourceSets (or a pattern matching them all). But yes I'll endeavor to fix this to work out of the box.

**Comment by jeremymailen** [comment]
It turns out its easily fixed by moving all the task creation logic to `project.afterEvaluate`. Then all the sourceSet configuration has finalized (I believe for subprojects too).

The only tricky bit: users would have to be very careful to do any customization/disabling of kotlinter created tasks (https://github.com/jeremymailen/kotlinter-gradle#customizing-tasks) wrapped in an `afterEvaluate { ... }` block. Otherwise they'd get an error since the task doesn't exist yet. Probably I'd want to rev this plugin to 2.0 since it would be a breaking change for some people's builds.

Thoughts?

**Comment by jeremymailen** [comment]
Thank you for the excellent analysis and suggestions @mikeholler. I appreciate your experience here!
If you are interested and have a little spare time now and again, I'd gladly add you as a contributor to the project.

Your suggestion for how to build it sounds both reasonable and doable. I'm assuming a `SourceSet` property can be marked as `@Input` to implement incremental build behavior? As far as modifying the files for an auto-created format or lint task, I had just imagined the use case and haven't seen it in real life yet. Creating a new custom source set seems fine. Not sure if the "filter some files out" use case exists in the wild.

I'll try to get to it this week or I'll update here if it's taking me longer.

**Comment by mikeholler** [comment]
Hey @jeremymailen,

Glad you liked my suggestions. `@Input` should be sufficient to get the source set to play nice with incremental build, but it's been a while since I've needed to rely on that part of the Gradle API. Still, something a quick check should be able to handle with ease.

Also happy to hear you like the suggestion to remove non-sourceset files. That definitely makes things simpler. If you plan on taking that route I'd suggest bumping the library's major version since it does break backward compatibility. And maybe documenting the migration path for other users.

And finally, I'd be happy to act as a collaborator. I won't be shy about suggesting changes/opening PRs here or there as I come across things, and you can feel free to tag me on something if you think I might be able to help.

Thanks for being so responsive and open to input.

**Comment by jeremymailen** [comment]
@mikeholler ☝️ I might need your help to fully test Android, but the new PR appeared to work well on Kotlin JVM projects

**Comment by mikeholler** [comment]
Thanks @jeremymailen, I'll review and test this in the next couple of days. I've got a couple _very_ busy days coming up, but I'll definitely try to give this the attention it deserves before the weekend.
