### ISSUE TITLE
Suppressing Warnings

### ISSUE THREAD

**Issue by rheasrivats** [jeremymailen/kotlinter-gradle#56]
Is there any satisfying way to suppress a certain error using this plugin? I tried using the ktlint disable command, as well as @Suppress in Kotlin and both failed, although I may be inputting the wrong string for @Suppress. Let me know if this is a supported feature.

**Comment by jeremymailen** [comment]
It supports the syntax described here: https://ktlint.github.io/#faq-error-suppression

I tested these cases and both worked for me:
```Kotlin
import some.package.* // ktlint-disable
import some.other.package.* // ktlint-disable no-wildcard-imports
```

Let me know if this works for you!

**Comment by rheasrivats** [comment]
So that works for me with wildcard imports -- however when I try to use it to disable a keyword-spacing rule both commands fail

**Comment by rheasrivats** [comment]
Oh wait nevermind I figured out the issue I was using the wrong rule
