### ISSUE TITLE
FilenameRule isn't applied when running lintKotlin task

### ISSUE THREAD

**Issue by timolehto** [jeremymailen/kotlinter-gradle#59]
Hi,

If I create a file `X.kt` with the following contents:

```
typealias NotX = Map<String, String>
```

And I run `ktlint` I get an error:

```
X.kt:1:1: typealias NotX should be declared in a file named NotX.kt
```

If I run:
```
./gradlew lintKotlin --rerun-tasks

BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed
```
No errors... why?

Related issue ticket on ktlint side: https://github.com/shyiko/ktlint/issues/230

**Comment by jeremymailen** [comment]
Thanks for the report, it appears none of the `FilenameRule` checks are working with kotlinter. From a quick look at the ktlint source, it seems there's a `file_path` userData key I need to pass in to ktlint. If that's what's missing I should be able to get this fixed in short order.

**Comment by timolehto** [comment]
I came to the same conclusion and actually already added some sort of maybe works support for that, but didn't get around to figuring out how to actually test it. I'm sure it's quite easy to implemet for you if even I almost managed to that. :)
