### ISSUE TITLE
Linter is not working for Android libraries

### ISSUE THREAD

**Issue by Tapchicoma** [jeremymailen/kotlinter-gradle#7]
Project has 2 modules - one is main application module and one is android library - linter tasks are created for library module, but doesn't report any issues in Kotlin files. I've checked by introducing "Needless blank line(s)" lint error.

**Comment by jeremymailen** [comment]
Thanks for bringing it to my attention Yahor. I haven't tested against more complex android projects so I might be missing some things. I'd like to figure out all the cases though and get them working!

Can you paste the output from `gradle tasks --all | grep lintKotlin` from the top of the project? This should help me see which sourceSets are being detected in the *library* module if any.

Are the lint tasks applied correctly to the source in the *application* module?

Can you run `gradle -d lintKotlin | grep linting`? This should show each file that is being detected and linted by the tasks. Let me know which source dirs it appears to be picking up and which ones it is missing.

Thanks for your help!

**Comment by jeremymailen** [comment]
I've found the issue and have a pull request to fix. Thanks for the report and I don't need any further info from you!

**Comment by jeremymailen** [comment]
https://github.com/jeremymailen/kotlinter-gradle/pull/8

**Comment by jeremymailen** [comment]
Should be fixed in `0.9.3`. Please give it a try and let me know if it works for you.
