### ISSUE TITLE
Make lint tasks cacheable?

### ISSUE THREAD

**Issue by autonomousapps** [jeremymailen/kotlinter-gradle#71]
Looking at your [LintTask](https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/LintTask.kt), I see that it is already incremental. Would you object to also making it [cacheable](https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details)? I believe it would be as simple as annotating the class with `@Cacheable`. And, since that annotation is not inherited by subclasses, you would also need to modify your [TaskCreator.createParentTasks()](https://github.com/jeremymailen/kotlinter-gradle/blob/master/src/main/kotlin/org/jmailen/gradle/kotlinter/KotlinterPlugin.kt#L63) function to make your dynamic tasks cacheable, using Gradle's runtime API. For example:

```
outputs.cacheIf { true }
```
I have tested this locally with my custom LintTask, and it works.
```
task lintKotlinAll(type: LintTask, group: 'verification') {
    outputs.cacheIf { true } // this enables the Gradle build cache
    source files(modulesToCheck.collect { "$it/src" }) // list of Gradle projects
    reports = [
            'plain': file("$buildDir/reports/ktlint/all-lint.txt"),
            'html' : file("$buildDir/reports/ktlint/all-lint.html")
    ]
}
```

If you're open to this, I would be willing to file a PR.

**Comment by jeremymailen** [comment]
Ah, great idea! I guess I forgot to keep up-to-date with the new Gradle build caching feature and what it requires.

Unless I misunderstand I _think_ since `lintKotlin` has no outputs and is just there to be a parent of the lint tasks for each source set, it always needs to run, but its child tasks will be cached or run incrementally depending on whether they are up to date?

**Comment by jeremymailen** [comment]
I other words, I'm hoping all I need to do to support build cache across the board is add the annotation to `LintTask`...

**Comment by cooperkong** [comment]
`formatKotlin` seems to be cached, I had to use `--rerun-tasks` to force it

**Comment by eskatos** [comment]
@jeremymailen if the task can already be UP-TO-DATE correctly, adding the `@CacheableTask` annotation will enable the Gradle build cache but it may only work with the local cache. For cached outputs to be shareable across machines via a remote cache they need to be "relocatable", and this may require extra care.

See https://guides.gradle.org/using-build-cache/#relocatability

**Comment by autonomousapps** [comment]
@jeremymailen yes, I mis-spoke. I don't think you need to use the runtime API in addition to `@CacheableTask`. @eskatos is right, though, about relocatability.

**Comment by jeremymailen** [comment]
Thanks for all the great input! Should be available now as soon as the gradle plugin portal publishes the latest.

@eskatos good notes, I'll have to study up but I'd guess my output reports are not relocatable without me doing a bit of work?

@cooperkong yes `formatKotlin` won't run again if it's already been run and the source files haven't changed. It's a feature, but unclear if it's useful in real world scenarios.

**Comment by autonomousapps** [comment]
@jeremymailen in the case of `LintTask`, I think that "relocatability" only refers to path sensitivity. See this paragraph from the link Paul provided:
> Tasks having files as inputs can declare the parts of a file’s path what are essential to them: this is called the [path sensitivity](https://docs.gradle.org/4.10.1/javadoc/org/gradle/api/tasks/PathSensitive.html) of the input. Task properties declared with ABSOLUTE path sensitivity are considered non-relocatable. This is the default for properties not declaring path sensitivity, too.

You can go to [this section](https://guides.gradle.org/using-build-cache/#dealing_with_file_paths) of the page to see an example of how to specify the path sensitivity of inputs and outputs. It's actually really straightforward (just as straightforward as adding `@CacheableTask`).

**Comment by cooperkong** [comment]
@jeremymailen Hi, this is what I did. Make an empty line, run `formatKotlin`, everything is fine. Then revert changes, run again, nothing happens. I had to use `--rerun-tasks`

**Comment by jeremymailen** [comment]
@cooperkong oh I see, there's an unusual case -- if you restore the input files to exactly the same state as when `formatKotlin` was run, it will think it is up-to-date because the report file is there with the same content. If you make any other changes to the source code it will re-run. Probably not worth making formatting incremental since this is rarely useful.

**Comment by jeremymailen** [comment]
https://github.com/jeremymailen/kotlinter-gradle/pull/73
