### ISSUE TITLE
Use Worker API for faster task execution

### ISSUE THREAD

**Issue by autonomousapps** [jeremymailen/kotlinter-gradle#82]
I just spiked some code to experiment with the [Worker API](https://guides.gradle.org/using-the-worker-api/) for `LintTask`, and in my sample build it cut task time roughly in half, from 10-11 seconds to 5-6 seconds. If you're open to it, I will submit a PR. Thanks for your consideration.

PS: If this works out, my next step would be to attempt to make the task incremental, meaning it would only process files that had changed, rather than every source file on every invocation.

**Comment by jeremymailen** [comment]
Yes, that would be awesome!

BTW, since `LintTask` extends `SourceTask` and defines the sourceSet as `@InputFiles` and report file as `@OutputFiles` it is incremental. You can see it if you:
```shell
gradle clean
gradle -d lintKotlin | grep linting
```
then do it again `gradle -d lintKotlin | grep linting`, change one file and repeat.

**Comment by autonomousapps** [comment]
Oh, great! I'll just stick with Workerizing it, then :-)

**Comment by jeremymailen** [comment]
Although the current incremental implementation sees an entire sourceSet as being up-to-date or out of date. Probably we could get to the file level of granularity using incremental task inputs?
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.incremental.IncrementalTaskInputs.html

**Comment by autonomousapps** [comment]
Yes, I believe that is necessary. Should have thought of that earlier :-)

**Comment by jeremymailen** [comment]
Worker API now utilized for faster linting _and_ formatting as of 1.25.0.
