### ISSUE TITLE
Dependency is not available?

### ISSUE THREAD

**Issue by cooperkong** [jeremymailen/kotlinter-gradle#90]
Hi
Was trying to upgrade to 1.21.0 but couldn't find the dependency under https://plugins.gradle.org/m2/gradle/plugin/org/jmailen/gradle/kotlinter-gradle/

**Comment by jeremymailen** [comment]
https://plugins.gradle.org/plugin/org.jmailen.kotlinter/1.21.0
Seems to be there and the instructions there for applying it (both styles) work for me.
Are you seeing an error running gradle?

**Comment by jeremymailen** [comment]
Also 1.23.0 is the latest right now.

**Comment by cooperkong** [comment]
Hi
Im getting `Could not find gradle.plugin.org.jmailen.gradle:kotlinter-gradle:1.23.0` when syncing project.
It's trying to find form `https://plugins.gradle.org/m2/gradle/plugin/org/jmailen/gradle/kotlinter-gradle/1.23.0/kotlinter-gradle-1.23.0.jar` and it's not there.

**Comment by jeremymailen** [comment]
It looks like you're using the wrong artifact coordinates. Gradle changed their conventions on how the publishing plugin mapped your project to a published maven artifact a while back allowing people to publish under their own namespace without the `gradle.plugin.org` preamble.

You'll find artifacts 1.16.0 and after here:
https://plugins.gradle.org/m2/org/jmailen/gradle/kotlinter-gradle/

So following https://plugins.gradle.org/plugin/org.jmailen.kotlinter/1.21.0:
```groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.jmailen.gradle:kotlinter-gradle:1.21.0"
  }
}

apply plugin: "org.jmailen.kotlinter"
```
